asymptomatics = [
  "2-methylbutyric aciduria",
  "2-methylbutyryl-coenzyme a dehydrogenase deficiency",
  "3 alpha methylcrotonyl-coa carboxylase 1 deficiency",
  "3 alpha methylcrotonyl-coa carboxylase 2 deficiency",
  "3-methylcrotonyl-coa carboxylase deficiency",
  "47,xxx syndrome",
  "aaa",
  "aarau dysfibrinogenemia",
  "abdominal cystic lymphangioma",
  "absent duct of santorini",
  "acad8 deficiency",
  "acanthoma",
  "acatalasemia",
  "accessory deep peroneal nerve",
  "accessory pancreas",
  "acid phosphatase deficiency",
  "acinic cell carcinoma",
  "ackee fruit food poisoning",
  "acral lentiginous melanoma",
  "acute elemental mercury inhalation",
  "acute myelosclerosis",
  "adenocarcinoid tumor",
  "adenocarcinoma of lung",
  "adenocarcinoma, bronchiolo-alveolar",
  "adenocarcinoma, clear cell",
  "adenocarcinoma, follicular",
  "adenosarcoma of the uterus",
  "adenosine monophosphate deaminase deficiency",
  "adrenal adenoma, familial",
  "adrenal cancer",
  "adrenal cortex neoplasms",
  "adrenal incidentaloma",
  "adrenocortical carcinoma",
  "alba/geneva i dysfibrinogenemia",
  "albers-schonberg disease -- adult benign dominant form",
  "albuminuria",
  "almeria i dysfibrinogenemia",
  "alpha thalassemia",
  "alpha thalassemia -- silent carrier",
  "alpha-n-acetylgalactosaminidase deficiency, type iii",
  "alveolar hydatid disease",
  "alveolar soft part sarcoma",
  "amebic dysentery",
  "amiens i dysfibrinogenemia",
  "amoebiasis",
  "amsterdam dysfibrinogenemia",
  "amyloid angiopathy",
  "anaplastic large cell lymphoma",
  "anaplastic small cell lymphoma",
  "anemia of pregnancy",
  "anesthetic agent-induced liver damage",
  "anesthetic agent-induced liver damage -- chloroform",
  "anesthetic agent-induced liver damage -- cyclopropane",
  "anesthetic agent-induced liver damage -- ether",
  "anesthetic agent-induced liver damage -- halothane",
  "anesthetic agent-induced liver damage -- methoxyflurane",
  "anesthetic agent-induced liver damage -- nitrous oxide",
  "aneurysm",
  "aneurysm of sinus of valsalva",
  "angiofollicular ganglionic hyperplasia",
  "angiofollicular ganglionic hyperplasia -- hyaline-vascular type",
  "angioimmunoblastic t-cell lymphoma",
  "angiosarcoma",
  "angiosarcoma of the breast",
  "angiosarcoma of the liver",
  "angiosarcoma of the scalp",
  "anguillulosis",
  "anthracosis",
  "antibiotics-induced liver damage",
  "antibiotics-induced liver damage -- cephalosporin",
  "antibiotics-induced liver damage -- chloramphenicol",
  "antibiotics-induced liver damage -- clindamycin",
  "antibiotics-induced liver damage -- erythromycin estolate",
  "antibiotics-induced liver damage -- erythromycin ethyl succinate",
  "antibiotics-induced liver damage -- nitrofuran",
  "antibiotics-induced liver damage -- novobiocin",
  "antibiotics-induced liver damage -- penicillin",
  "antibiotics-induced liver damage -- quinolone",
  "antibiotics-induced liver damage -- rifampicin",
  "antibiotics-induced liver damage -- spectinomycin",
  "antibiotics-induced liver damage -- sulfones",
  "antibiotics-induced liver damage -- telithromycin",
  "antibiotics-induced liver damage -- tetracycline",
  "anticonvulsive-induced liver damage",
  "anticonvulsive-induced liver damage -- mephenytoin",
  "anticonvulsive-induced liver damage -- phenobarbital",
  "anticonvulsive-induced liver damage -- phenytoin",
  "anticonvulsive-induced liver damage -- valproic acid",
  "antifungal agent-induced liver damage",
  "antifungal agent-induced liver damage -- 5-fluorocytosine",
  "antifungal agent-induced liver damage -- amphotericin",
  "antifungal agent-induced liver damage -- griseofulvin",
  "antifungal agent-induced liver damage -- ketoconazole",
  "antifungal agent-induced liver damage -- saramycetin",
  "antimetazoal agent-induced liver damage",
  "antimetazoal agent-induced liver damage -- amodiaquine",
  "antimetazoal agent-induced liver damage -- hycanthone",
  "antiprotozoal agent-induced liver damage",
  "antiprotozoal agent-induced liver damage -- 8-hydroxyquinolone",
  "antiprotozoal agent-induced liver damage -- carbarsone",
  "antiprotozoal agent-induced liver damage -- emetine",
  "antiprotozoal agent-induced liver damage -- mepacrine",
  "antiprotozoal agent-induced liver damage -- metronidazole",
  "antiprotozoal agent-induced liver damage -- thiabendazole",
  "antituberculous agent-induced liver damage",
  "antituberculous agent-induced liver damage -- cycloserine",
  "antituberculous agent-induced liver damage -- ethionamide",
  "antituberculous agent-induced liver damage -- isoniazid",
  "antituberculous agent-induced liver damage -- p-aminosalicylic acid",
  "antituberculous agent-induced liver damage -- rifampicin",
  "antiviral agent-induced liver damage",
  "antiviral agent-induced liver damage -- cytarabine",
  "antiviral agent-induced liver damage -- idoxuridine",
  "antiviral agent-induced liver damage -- vidarabine",
  "antiviral agent-induced liver damage -- xenylamine",
  "aortic aneurysm, thoracic",
  "aortic stenosis",
  "aortic valve incompetence",
  "aortic valves stenosis of the child",
  "aorto-ventricular tunnel",
  "appendiceal tumor",
  "appendix cancer",
  "arachnoid cysts",
  "arbovirosis",
  "arnold-chiari malformation (type 1)",
  "arrhythmias",
  "arrhythmogenic right ventricular dysplasia, familial, 1",
  "arrhythmogenic right ventricular dysplasia, familial, 10",
  "arrhythmogenic right ventricular dysplasia, familial, 11",
  "arrhythmogenic right ventricular dysplasia, familial, 12",
  "arrhythmogenic right ventricular dysplasia, familial, 2",
  "arrhythmogenic right ventricular dysplasia, familial, 3",
  "arrhythmogenic right ventricular dysplasia, familial, 4",
  "arrhythmogenic right ventricular dysplasia, familial, 5",
  "arrhythmogenic right ventricular dysplasia, familial, 6",
  "arrhythmogenic right ventricular dysplasia, familial, 7",
  "arrhythmogenic right ventricular dysplasia, familial, 8",
  "arrhythmogenic right ventricular dysplasia, familial, 9",
  "ascariasis",
  "asymmetric septal hypertrophy",
  "asymptomatic inflammatory prostatitis",
  "atherosclerosis",
  "atrial arrhythmia",
  "atrial flutter",
  "atrial myxoma, familial",
  "atrial septal defect",
  "atrial septal defect 1",
  "atrial septal defect 2",
  "atrial septal defect 3",
  "atrial septal defect 4",
  "atrial septal defect 5",
  "atrial septal defect 6",
  "attenuated familial polyposis",
  "autoimmune hemolytic anemia",
  "autoimmune thrombocytopenia",
  "b-cell chronic lymphocytic leukemia",
  "babesiosis",
  "bacterial vaginosis",
  "balantidiasis",
  "bantu siderosis",
  "baritosis",
  "bartter's syndrome, type 3",
  "baylisascaris",
  "bednar's tumor",
  "benson disease",
  "bertielliasis",
  "best vitelliform macular dystrophy",
  "bethesda ii dysfibrinogenemia",
  "bicuspid aortic valve",
  "bidirectional tachycardia",
  "bile duct cancer, extrahepatic",
  "biliary tract cancer",
  "bk virus infection",
  "bladder diverticulum",
  "blastocystis hominis",
  "blastoma",
  "blastomycosis",
  "bone and cartilage tumors",
  "bone cancer",
  "bone infarct",
  "breast cancer",
  "breast carcinoma",
  "brenner tumor",
  "brenner tumor of the vagina",
  "brucellosis",
  "bundle branch block",
  "calcification of basal ganglia with or without hypocalcemia",
  "california encephalitis",
  "campylobacter fetus infection",
  "campylobacter food poisoning",
  "campylobacter hylointestinalis infection",
  "campylobacter jejuni infection",
  "campylobacter laridis infection",
  "cardiac diverticulum",
  "cardiac malformation",
  "cardiomyopathy due to anthracyclines",
  "carrier conditions",
  "cartilaginous neoplasms",
  "cataracts",
  "celiac artery stenosis from compression by median arcuate ligament of diaphragm",
  "celiac disease",
  "cerebral aneurysm",
  "cerebral astrocytoma, adult",
  "cervical cancer",
  "cervical intraepithelial neoplasia",
  "chiari-1 malformation",
  "chilaiditi syndrome",
  "childhood liver cancer, primary",
  "chlamydia",
  "chlamydial infection",
  "chloramphenicol-induced sideroblastic anemia",
  "chloroma",
  "chloromyeloma",
  "cholera",
  "cholestasis",
  "chondrosarcoma (malignant)",
  "choroid plexus cyst",
  "choroiditis, serpiginous",
  "chromophil renal cell carcinoma",
  "chromophobe renal cell carcinoma",
  "chromosome 10, uniparental disomy of",
  "chromosome 17 trisomy mosaicism",
  "chromosome 21 ring",
  "chromosome 7, trisomy mosaic",
  "chromosome 8, mosaic trisomy",
  "chronic anemia",
  "chronic benign neutropenia",
  "chronic kidney failure",
  "chronic leukemia",
  "chronic silicosis",
  "ciliary dyskinesia, due to transposition of ciliary microtubules",
  "cin",
  "cirrhotic cardiomyopathy",
  "citrullinemia i, later-onset",
  "clear cell renal cell carcinoma",
  "cleveland dysfibrinogenemia",
  "coal worker's pneumoconiosis",
  "coarctation of aorta autosomal dominant",
  "coats disease",
  "cobalamin pseudodeficiency due to transcobalamin deficiency",
  "cobalamin r binder protein deficiency",
  "coccidioidomycosis",
  "cold autoimmune hemolytic anemia",
  "cold sores",
  "collecting duct carcinoma",
  "colloid cysts of third ventricle",
  "coloboma of iris",
  "colonic diverticulosis",
  "colonic malakoplakia",
  "colorectal cancer",
  "colorectal cancer, susceptibility to, 1",
  "colorectal cancer, susceptibility to, 10",
  "colorectal cancer, susceptibility to, 11",
  "colorectal cancer, susceptibility to, 2",
  "colorectal cancer, susceptibility to, 3",
  "colorectal cancer, susceptibility to, 4",
  "colorectal cancer, susceptibility to, 5",
  "colorectal cancer, susceptibility to, 6",
  "colorectal cancer, susceptibility to, 7",
  "colorectal cancer, susceptibility to, 8",
  "colorectal cancer, susceptibility to, 9",
  "colorectal polyps",
  "congenital analbuminemia",
  "congenital aneurysms of the great vessels",
  "congenital arteriovenous shunt",
  "congenital bronchogenic cyst",
  "congenital cardiovascular malformations",
  "congenital fiber type disproportion",
  "congenital heart block",
  "congenital heart septum defect",
  "congenital hypothyroidism",
  "congenital mesoblastic nephroma",
  "congenital mitral malformation",
  "congenital mitral stenosis",
  "congenital syphilis",
  "congenital thrombotic disease due to protein c deficiency",
  "copper deficiency-induced sideroblastic anemia",
  "corneal graft rejection",
  "corneal transplant rejection",
  "coronary arteries -- congenital malformation",
  "coronary artery aneurysm",
  "coronary heart disease",
  "corticosteroid-binding globulin deficiency",
  "cryofibrinogenemia",
  "cryptococcosis",
  "cycloserine-induced sideroblastic anemia",
  "cyclosporiasis",
  "cyclosporiosis",
  "cysticercosis",
  "cytomegalovirus",
  "dandy-walker variant",
  "deafness -- thyroid hormone resistance",
  "decreased mean cell haemoglobin",
  "decreased mean cell haemoglobin concentration",
  "decreased mean cell volume",
  "decreased sugar tolerance in diabetics",
  "deep vein thrombosis",
  "deficiency of member 8 acyl-coa dehydrogenace family",
  "dehydratase deficiency",
  "dermatofibrosarcoma protuberans",
  "dermoid cyst",
  "desmoid disease, hereditary",
  "desmoplastic small round cell tumor",
  "developmental delay due to 2-methylbutyryl-coa dehydrogenase deficiency",
  "dextrocardia",
  "diabetes",
  "diabetes mellitus, noninsulin-dependent, susceptibility to, 1",
  "diabetes mellitus, noninsulin-dependent, susceptibility to, 2",
  "diabetes mellitus, noninsulin-dependent, susceptibility to, 3",
  "diabetes mellitus, noninsulin-dependent, susceptibility to, 4",
  "diabetic nephropathy",
  "diaphragmatic hernia, congenital",
  "dibasic aminoaciduria type 1",
  "dic",
  "dientamoeba fragilis",
  "digestive duplication",
  "digestive tract cancer",
  "dilated cardiomyopathy",
  "dimorphic anemia",
  "diphyllobothriasis",
  "diphyllobothrium latum infection",
  "dipylidiasis",
  "diverticular disease",
  "diverticular disease and diverticulitis",
  "dowling-degos disease",
  "doxorubicin-induced cardiomyopathy",
  "dracunculiasis",
  "drug-induced liver damage -- 5-fluorocytosine",
  "drug-induced liver damage -- allopurinol",
  "drug-induced liver damage -- amphotericin",
  "drug-induced liver damage -- anabolic c-17",
  "drug-induced liver damage -- anesthetic agent",
  "drug-induced liver damage -- antianginal agents",
  "drug-induced liver damage -- antiarrhythmics",
  "drug-induced liver damage -- antibiotics",
  "drug-induced liver damage -- anticoagulants",
  "drug-induced liver damage -- anticonvulsives",
  "drug-induced liver damage -- antifungals",
  "drug-induced liver damage -- antihyperlipidemic agents",
  "drug-induced liver damage -- antihypertensives",
  "drug-induced liver damage -- antineoplastic agents",
  "drug-induced liver damage -- antithyroid drugs",
  "drug-induced liver damage -- antituberculous agents",
  "drug-induced liver damage -- antiviral medication",
  "drug-induced liver damage -- benzodiazepine",
  "drug-induced liver damage -- british anti-lewisite penicillamine",
  "drug-induced liver damage -- butyrophenone",
  "drug-induced liver damage -- cephalosporin",
  "drug-induced liver damage -- chloramphenicol",
  "drug-induced liver damage -- chloroform",
  "drug-induced liver damage -- cimetidine",
  "drug-induced liver damage -- clindamycin",
  "drug-induced liver damage -- colchicine",
  "drug-induced liver damage -- cyclopropane",
  "drug-induced liver damage -- cycloserine",
  "drug-induced liver damage -- cytarabine",
  "drug-induced liver damage -- dantrolene",
  "drug-induced liver damage -- diflunisal",
  "drug-induced liver damage -- disulfiram",
  "drug-induced liver damage -- diuretic agents",
  "drug-induced liver damage -- endocrine agent",
  "drug-induced liver damage -- erythromycin estolate",
  "drug-induced liver damage -- erythromycin ethyl succinate",
  "drug-induced liver damage -- ethionamide",
  "drug-induced liver damage -- fenoprofen",
  "drug-induced liver damage -- glucocorticoids",
  "drug-induced liver damage -- griseofulvin",
  "drug-induced liver damage -- halothane",
  "drug-induced liver damage -- ibuprofen",
  "drug-induced liver damage -- idoxuridine",
  "drug-induced liver damage -- indomethacin",
  "drug-induced liver damage -- iodide ion",
  "drug-induced liver damage -- isoniazid",
  "drug-induced liver damage -- ketoconazole",
  "drug-induced liver damage -- mephenytoin",
  "drug-induced liver damage -- methoxyflurane",
  "drug-induced liver damage -- monoamine oxidase inhibitors",
  "drug-induced liver damage -- naproxen",
  "drug-induced liver damage -- nitrofuran",
  "drug-induced liver damage -- nitrous oxide",
  "drug-induced liver damage -- novobiocin",
  "drug-induced liver damage -- oral hypoglycemics",
  "drug-induced liver damage -- p-aminosalicylic acid",
  "drug-induced liver damage -- penicillin",
  "drug-induced liver damage -- phenobarbital",
  "drug-induced liver damage -- phenothiazines",
  "drug-induced liver damage -- phenylbutazone",
  "drug-induced liver damage -- phenytoin",
  "drug-induced liver damage -- psychotropic agents",
  "drug-induced liver damage -- quinolone",
  "drug-induced liver damage -- ranitidine",
  "drug-induced liver damage -- rifampicin",
  "drug-induced liver damage -- salicylate",
  "drug-induced liver damage -- saramycetin",
  "drug-induced liver damage -- spectinomycin",
  "drug-induced liver damage -- steroids",
  "drug-induced liver damage -- sulfonamide",
  "drug-induced liver damage -- sulfones",
  "drug-induced liver damage -- sulindac",
  "drug-induced liver damage -- tamoxifen",
  "drug-induced liver damage -- telithromycin",
  "drug-induced liver damage -- tetracycline",
  "drug-induced liver damage -- thioxanthene",
  "drug-induced liver damage -- thorotrast",
  "drug-induced liver damage -- tricyclic antidepressant",
  "drug-induced liver damage -- valproic acid",
  "drug-induced liver damage -- vidarabine",
  "drug-induced liver damage -- vitamin a",
  "drug-induced liver damage -- xenylamine",
  "drug-induced liver damage -- zoxazolamine",
  "drug-induced sideroblastic anemia",
  "drugs-induced liver damage -- ether",
  "dysfibrinogenemia, familial",
  "dysgerminoma",
  "eagle's syndrome",
  "ebstein's anomaly",
  "emphysema, congenital lobar",
  "endocrine agent-induced liver damage",
  "endocrine agent-induced liver damage -- anabolic c-17",
  "endocrine agent-induced liver damage -- antithyroid drugs",
  "endocrine agent-induced liver damage -- glucocorticoids",
  "endocrine agent-induced liver damage -- oral contraceptives",
  "endocrine agent-induced liver damage -- oral hypoglycemics",
  "endocrine agent-induced liver damage -- steroids",
  "endocrine agent-induced liver damage -- tamoxifen",
  "endodermal sinus tumor",
  "endolymphatic sac tumors (elst's) in von hippel lindau (vhl) disease",
  "endometrial stromal sarcoma",
  "endometriosis",
  "epstein-barr virus",
  "erdheim disease i",
  "escherichia coli o157:h7",
  "esophageal carcinoma",
  "esophageal diverticulum",
  "esophagus cancer",
  "essential thrombocytosis -- same as essential thrombocythemia",
  "ethanol-induced sideroblastic anemia",
  "ewing's family of tumors",
  "exostoses",
  "extragonadal germ cell tumor",
  "extramedullary myeloid tumor",
  "extranodal marginal zone b-cell lymphoma of mucosa-associated lymphoid tissue",
  "factor vii deficiency",
  "factor xii deficiency",
  "fahr's syndrome",
  "fallopian tube cancer",
  "familial chronic benign neutropenia",
  "familial colorectal cancer",
  "familial dysalbuminemic hyperthyroxinemia",
  "familial hypertension",
  "familial hypertrophic cardiomyopathy 1",
  "familial hypertrophic cardiomyopathy 10",
  "familial hypertrophic cardiomyopathy 2",
  "familial hypertrophic cardiomyopathy 3",
  "familial hypertrophic cardiomyopathy 4",
  "familial hypertrophic cardiomyopathy 5",
  "familial hypertrophic cardiomyopathy 6",
  "familial hypertrophic cardiomyopathy 7",
  "familial hypertrophic cardiomyopathy 8",
  "familial hypertrophic cardiomyopathy 9",
  "familial polyposis -- classical",
  "familial polyposis, autosomal recessive",
  "familial pulmonary arterial hypertension",
  "familial visceral myopathy",
  "familial wilms tumor 2",
  "fasciolopsiasis",
  "fetal left ventricular aneurysm",
  "florid cystic endosalpingiosis of the uterus",
  "folate-deficiency anemia",
  "follicular dendritic cell tumor",
  "fructose-1-phosphate aldolase deficiency, hereditary",
  "fructosuria",
  "galactosemia iii",
  "gall bladder cancer",
  "gallstones",
  "gamma-cystathionase deficiency",
  "gastric cancer, borrmann 4",
  "gastric lymphoma",
  "gastro-enteropancreatic neuroendocrine tumor",
  "gastrointestinal neoplasm",
  "gastrointestinal stromal tumors",
  "gastrointestinal tumors",
  "generalized resistance to thyroid hormone",
  "genital herpes",
  "genochondromatosis",
  "genochondromatosis ii",
  "geographic tongue",
  "gestational diabetes",
  "gestational hypertension",
  "gestational trophoblastic tumor",
  "ghost cell glaucoma",
  "giardia",
  "gilbert's syndrome",
  "glaucoma",
  "glaucoma acquired secondary to intraocular neoplasm",
  "glaucoma, hereditary",
  "glioma",
  "glioma susceptibility",
  "glioma susceptibility 1",
  "glioma susceptibility 2",
  "glioma susceptibility 3",
  "glioma susceptibility 4",
  "glioma susceptibility 5",
  "glioma susceptibility 6",
  "glioma susceptibility 7",
  "glioma susceptibility 8",
  "glomerulonephritis",
  "glomerulosclerosis",
  "glomus vagale tumors",
  "glucocorticoid resistance",
  "glucose-6-phosphate dehydrogenase deficiency",
  "glue ear",
  "glyceraldehyde-3-phosphate dehydrogenase deficiency",
  "glycogenosis type 8",
  "gonorrhea",
  "gout",
  "graeck-imerslund disease",
  "granuloma annulare",
  "granulosa cell tumor of the ovary",
  "grasbeck-imerslund disease",
  "graves disease",
  "group a streptococcal infections",
  "hageman factor deficiency",
  "hashimoto's thyroiditis",
  "heart block progressive, familial",
  "helicobacter cinaedi infection",
  "helicobacter fenneliae infection",
  "heller-dohle disease",
  "helminthiasis",
  "hemangioblastoma",
  "hemochromatosis",
  "hemoglobin d trait (ad)",
  "hemoglobin e trait",
  "hemoglobin s-g (s-d)",
  "hemoglobin, constant spring",
  "hemoglobinopathy",
  "hemolytic anemia",
  "hemospermia",
  "heparin-induced thrombocytopenia",
  "hepatitis",
  "hepatitis a",
  "hepatitis b",
  "hepatitis c",
  "hepatitis g",
  "hepatocellular carcinoma (fibrolamellar variant)",
  "hepatoma",
  "heptaosplenic t-cell lymphoma",
  "hereditary elliptocytosis",
  "hereditary macrothrombocytopenia",
  "hereditary megaduodenum",
  "hereditary methemoglobinemia, recessive",
  "hereditary spherocytic hemolytic anemia",
  "heterophyiasis",
  "heterozygous beta-thalassemia 1",
  "heterozygous beta-thalassemia 2",
  "heterozygous familial hypercholesterolemia",
  "hiatal hernia",
  "high blood pressure/hypertension",
  "high cholesterol",
  "histoplasmosis",
  "hiv/aids",
  "homozygous familial hypercholesterolemia",
  "homozygous hypobetalipoproteinemia",
  "horseshoe kidney",
  "htlv",
  "htlv-1",
  "human papillomavirus",
  "hydatidiform mole",
  "hydatidosis",
  "hydronephrosis",
  "hydronephrosis congenital",
  "hymenolepiasis",
  "hyperchromic anemia",
  "hyperhomocysteinemia",
  "hyperlipoproteinemia",
  "hyperlysinemia, persistent",
  "hyperparathyroidism",
  "hyperphenilalaninemia due to pterin-4-alpha-carbinolamine dehydratase deficiency",
  "hyperphenylalaninemia with primapterinuria",
  "hyperphosphataemia",
  "hyperprolinaemia type i",
  "hyperprolinemia",
  "hyperprolinemia type i",
  "hyperprolinemia type ii",
  "hypertension",
  "hypertension in children",
  "hypertension in children from 11 through adolescence",
  "hypertension in children one to ten years",
  "hypertension in children under one year",
  "hypertension of pregnancy",
  "hypertension, essential",
  "hypertension, essential, susceptibility to",
  "hypertension, essential, susceptibility to, 1",
  "hypertension, essential, susceptibility to, 2",
  "hypertension, essential, susceptibility to, 3",
  "hypertension, essential, susceptibility to, 4",
  "hypertension, essential, susceptibility to, 5",
  "hypertension, essential, susceptibility to, 6",
  "hypertension, essential, susceptibility to, 7",
  "hypertension, essential, susceptibility to, 8",
  "hypertension-like disorders",
  "hypertrophic cardiomyopathy",
  "hypobetalipoproteinemia",
  "hypobetalipoproteinemia, familial",
  "hypocalcemia, autosomal dominant",
  "hypocalciuric hypercalcemia, familial",
  "hypocalciuric hypercalcemia, familial, type 1",
  "hypocalciuric hypercalcemia, familial, type 2",
  "hypocalciuric hypercalcemia, familial, type 3",
  "hypolipoproteinemia",
  "ichthyosis vulgaris, dominant",
  "idiopathic dilatation of the pulmonary artery",
  "idiopathic minimal change nephrotic syndrome",
  "idiopathic pulmonary hypertension",
  "idiopathic sclerosing mesenteritis",
  "idiopathic subglottic tracheal stenosis",
  "iminoglycinuria",
  "immotile cilia syndrome, due to defective radial spokes",
  "immotile cilia syndrome, due to excessively long cilia",
  "immune thrombocytopenia",
  "impaired glucose tolerance",
  "inflammatory myofibroblastic tumors",
  "internal carotid agenesis",
  "intracranial germ cell tumour",
  "intrauterine infections",
  "iodine antenatal infection",
  "iridodialysis",
  "iron deficiency anemia",
  "isobutyric aciduria",
  "isobutyryl-coenzyme a dehydrogenase deficiency",
  "isoniazid-induced sideroblastic anemia",
  "japanese encephalitis",
  "jc virus infection",
  "juvenile osteoporosis",
  "juvenile paget's disease",
  "juvenile temporal arteritis",
  "kaolin pneumoconiosis",
  "kidney cancer",
  "kidney damage -- 1,2-dichloromethane",
  "kidney damage -- acetaminophen",
  "kidney damage -- aminoglycosides",
  "kidney damage -- aminosalicylic acid",
  "kidney damage -- amphotericin b",
  "kidney damage -- amyl alcohol",
  "kidney damage -- analgesics",
  "kidney damage -- anti-cancer drugs",
  "kidney damage -- antibiotics",
  "kidney damage -- aristolochic acid",
  "kidney damage -- arsenic",
  "kidney damage -- aspirin",
  "kidney damage -- automobile exhaust",
  "kidney damage -- bacitracin",
  "kidney damage -- bismuth",
  "kidney damage -- cadmium",
  "kidney damage -- carbon tetrachloride",
  "kidney damage -- cephaloridine",
  "kidney damage -- chloroform",
  "kidney damage -- chlortetracycline",
  "kidney damage -- chromium",
  "kidney damage -- cisplatin",
  "kidney damage -- contrast agents",
  "kidney damage -- copper",
  "kidney damage -- cyclophosphamide",
  "kidney damage -- cyclosporin",
  "kidney damage -- degreasing solvents",
  "kidney damage -- dichloroacetylene",
  "kidney damage -- diethylene glycol",
  "kidney damage -- dioxane",
  "kidney damage -- ethylene glycol",
  "kidney damage -- ethylene glycol ethers",
  "kidney damage -- fuels",
  "kidney damage -- gasoline",
  "kidney damage -- germanium",
  "kidney damage -- glue solvent vapors",
  "kidney damage -- glues",
  "kidney damage -- gold",
  "kidney damage -- hairdressing solvents",
  "kidney damage -- hairdressing sprays",
  "kidney damage -- heavy metals",
  "kidney damage -- herbicide",
  "kidney damage -- hexachloro-1,3-butadiene",
  "kidney damage -- hydrocarbons",
  "kidney damage -- ibuprofen",
  "kidney damage -- lead",
  "kidney damage -- lithium",
  "kidney damage -- mercury",
  "kidney damage -- methanol",
  "kidney damage -- methemoglobin-producing agents",
  "kidney damage -- methicillin",
  "kidney damage -- neomycin",
  "kidney damage -- nonsteroidal anti-inflammatory drugs",
  "kidney damage -- oxytetracycline",
  "kidney damage -- paint solvents",
  "kidney damage -- paint thinners",
  "kidney damage -- paints",
  "kidney damage -- paraquat ochratoxin a",
  "kidney damage -- perchloroethylene",
  "kidney damage -- pesticide solvents",
  "kidney damage -- pesticides",
  "kidney damage -- platinum",
  "kidney damage -- polymyxin",
  "kidney damage -- prostaglandin synthetase inhibitors",
  "kidney damage -- rifampin",
  "kidney damage -- silica",
  "kidney damage -- silicon compounds",
  "kidney damage -- silver",
  "kidney damage -- solvents",
  "kidney damage -- styrene",
  "kidney damage -- sulphonamides",
  "kidney damage -- thallium",
  "kidney damage -- toluene",
  "kidney damage -- trichloroethane",
  "kidney damage -- trichloroethylene",
  "kidney damage -- trimethropin",
  "kidney damage -- uranium",
  "kidney damage due to chemicals",
  "kidney disease-induced hypertension",
  "kidney stones",
  "klinefelter syndrome",
  "kohler syndrome",
  "labile hypertension",
  "labrador lung",
  "lactate dehydrogenase deficiency type b",
  "lactate dehydrogenase deficiency type c",
  "langerhans cell histiocytosis",
  "langerhans cell sarcoma",
  "large granular lymphocyte leukemia",
  "laryngocele",
  "laryngomalacia",
  "laryngomalacia, dominant congenital",
  "latent tuberculosis",
  "leber miliary aneurysm",
  "ledderhose disease",
  "left-sided gallbladder",
  "legionella adelaidensis infection",
  "legionella anisa infection",
  "legionella beliardensis infection",
  "legionella birminghamensis infection",
  "legionella bozemanii infection",
  "legionella bruneiensis infection",
  "legionella brunensis infection",
  "legionella busanensis infection",
  "legionella cherrii infection",
  "legionella cincinnatiensis infection",
  "legionella donaldsonii infection",
  "legionella donaldsonil infection",
  "legionella drancourtii infection",
  "legionella drozanskii infection",
  "legionella dumofii infection",
  "legionella erythra infection",
  "legionella fairfieldensis infection",
  "legionella fallonii infection",
  "legionella feelei infection",
  "legionella feeleii infection",
  "legionella gesstiana infection",
  "legionella gormanii infection",
  "legionella gratiana infection",
  "legionella gresilensis infection",
  "legionella hackeliae infection",
  "legionella impletisoli infection",
  "legionella isrealensis infection",
  "legionella jamestowniensis infection",
  "legionella jordanis infection",
  "legionella lansingensis infection",
  "legionella londinensis infection",
  "legionella longbeachae infection",
  "legionella lytica infection",
  "legionella maceachemii infection",
  "legionella maceachernii infection",
  "legionella micdadei infection",
  "legionella monrovica infection",
  "legionella moravica infection",
  "legionella nautarum infection",
  "legionella oakridgensis infection",
  "legionella parisiensis infection",
  "legionella quateirensis infection",
  "legionella quinlivanii infection",
  "legionella rowbothamii infection",
  "legionella rubrilucens infection",
  "legionella sainthelensi infection",
  "legionella santicrucis infection",
  "legionella shakespearei infection",
  "legionella spiritensis infection",
  "legionella steigerwaltii infection",
  "legionella tauriensis infection",
  "legionella tusconensis infection",
  "legionella wadsorthii infection",
  "legionella wadsworthii infection",
  "legionella waltersii infection",
  "legionella worsliensis infection",
  "legionella yabuuchiae infection",
  "legionnaires' disease",
  "leiomyosarcoma",
  "leptospirosis",
  "leukemia",
  "leukemia, b-cell, chronic",
  "leukemia, mast-cell",
  "leukemia, t-cell, chronic",
  "leukodystrophy, pseudometachromatic",
  "leukoplakia",
  "lip and oral cavity cancer",
  "lipoma",
  "lipomatous hemangiopericytoma",
  "lipoproteinemia",
  "listeriosis of pregnancy",
  "liver cancer",
  "los angeles dysfibrinogenemia",
  "lung herniation -- congenital defect of sternum",
  "lymphatic filariasis",
  "lymphatic neoplasm",
  "lymphatic system cancer",
  "lymphatic system tumors",
  "lymphedema, hereditary",
  "macrocytic anemia",
  "macrocytic hyperchromic anemia",
  "male breast cancer",
  "malformations in neuronal migration",
  "malignant germ cell tumor",
  "malignant mesenchymal tumor",
  "malignant mixed mullerian tumor",
  "malignant rhabdoid tumors",
  "malignant teratocarcinosarcoma",
  "mansonella ozzardi infection",
  "mansonella streptocerca infection",
  "marchiafava-micheli disease",
  "mast cell sarcoma",
  "may-hegglin anomaly",
  "may-hegglin thrombocytopenia",
  "mazabraud syndrome",
  "mediastinal endodermal sinus tumors",
  "medication induced osteoporosis",
  "megaduodenum",
  "megaduodenum and/or megacystis",
  "megaloblastic anemia 1",
  "megalocytic interstitial nephritis",
  "megalocytic-normochromic anemia",
  "membranoproliferative glomerulonephritis",
  "membranoproliferative glomerulonephritis (type 2)",
  "membranoproliferative glomerulonephritis, x-linked",
  "meningocele",
  "meningomyelocele",
  "mesangiocapillary glomerulonephritis type 1",
  "mesangiocapillary glomerulonephritis type iii",
  "mesothelioma",
  "metastatic squamous neck cancer with occult primary",
  "methionine adenosyltransferase deficiency",
  "methylene tetrahydrofolate reductase deficiency",
  "methylmalonic acidemia, synthesis defect of adocbl and mecbl",
  "microcytic hyperchromic anemia",
  "microcytic-normochromic anemia",
  "microencephaly",
  "mild hypercalcemia",
  "mitral regurgitation",
  "mitral stenosis",
  "mitral valve prolapse, familial",
  "mitral valve prolapse, familial, autosomal dominant",
  "mitral valve prolapse, familial, x-linked",
  "mitral valve prolapse, myxomatous 1",
  "mitral valve prolapse, myxomatous 2",
  "mitral valve prolapse, myxomatous 3",
  "mitral-valve prolapse",
  "mixed or combined mechanism glaucoma",
  "mondini dysplasia",
  "monoclonal gammopathy of undetermined significance",
  "morel-wildi syndrome",
  "multi-centric castleman's disease",
  "multicystic renal dysplasia",
  "multifocal ventricular premature beats",
  "multiple hereditary exostoses",
  "multiple myeloma",
  "mycotoxin-induced liver damage -- aflatoxin",
  "mycotoxin-induced liver damage -- cyclochlorotine",
  "mycotoxin-induced liver damage -- luteoskyrins",
  "mycotoxin-induced liver damage -- ochratoxin",
  "mycotoxin-induced liver damage -- rubratoxin",
  "mycotoxin-induced liver damage -- sterigmatocystin",
  "myelofibrosis-osteosclerosis",
  "myeloid sarcoma",
  "myeloperoxidase deficiency",
  "myoadenylate deaminase deficiency",
  "myoglobinuria",
  "myopathy, congenital fiber-type disproportion",
  "myosarcoma",
  "myositis ossificans post-traumatic",
  "myxozoa",
  "n-acetyl-alpha-d-galactosaminidase",
  "nancy dysfibrinogenemia",
  "nasopharyngeal carcinoma",
  "nasopharynx cancer",
  "neonatal herpes, type 2 virus",
  "neonatal ovarian cyst",
  "nephrocalcinosis",
  "nephrosclerosis",
  "neuroblastoma, susceptibility to",
  "neuroblastoma, susceptibility to, 1",
  "neuroblastoma, susceptibility to, 2",
  "neuroblastoma, susceptibility to, 3",
  "neuroblastoma, susceptibility to, 4",
  "neuroblastoma, susceptibility to, 5",
  "neuroblastoma, susceptibility to, 6",
  "neuroectodermal tumor, primitive",
  "neuroectodermal tumors primitive",
  "neuroendocrine carcinoma of the cervix",
  "neuroepithelioma",
  "neurofibromatosis, familial intestinal",
  "neurofibrosarcoma",
  "neuroma biliary tract",
  "neurosyphilis -- asymptomatic",
  "nodular melanoma",
  "non functioning pancreatic endocrine tumor",
  "non-alcoholic steatohepatitis (nash)",
  "non-specific urethritis",
  "normochromic anemia",
  "normocytic anemia",
  "normocytic-normochromic anemia",
  "nutritional anemia",
  "nutritional sideroblastic anemia",
  "occupational cancer -- liver cancer",
  "occupational cancer -- lymphatic cancer",
  "occupational cancer -- mesothelioma",
  "occupational cancer -- nasal cavity and sinus cancer",
  "occupational cancer -- non-hodgkin's lymphoma",
  "occupational cancer -- soft tissue sarcoma",
  "occupational liver damage -- 1,1,1-tetrachloroethane",
  "occupational liver damage -- 1,1,2-tetrachloroethane",
  "occupational liver damage -- 1,2-dibromoethane",
  "occupational liver damage -- 1,2-dichloroethane",
  "occupational liver damage -- 2-acetylamino-fluorene",
  "occupational liver damage -- 2-nitropropane",
  "occupational liver damage -- 3,3-dichlorobenzidine",
  "occupational liver damage -- 4-dimethylaminoazobenzene",
  "occupational liver damage -- acetates",
  "occupational liver damage -- acetonitrile",
  "occupational liver damage -- acrylonitrile",
  "occupational liver damage -- alcohol",
  "occupational liver damage -- alicyclic hydrocarbons",
  "occupational liver damage -- aliphatic amines",
  "occupational liver damage -- aliphatic hydrocarbons",
  "occupational liver damage -- aliphatic hydrogenated hydrocarbons",
  "occupational liver damage -- allyl alcohol",
  "occupational liver damage -- amyl acetate",
  "occupational liver damage -- aromatic amines",
  "occupational liver damage -- aromatic halogenated hydrocarbons",
  "occupational liver damage -- aromatic hydrocarbons",
  "occupational liver damage -- arsenic",
  "occupational liver damage -- arsine",
  "occupational liver damage -- benzene",
  "occupational liver damage -- benzyl chloride",
  "occupational liver damage -- beryllium",
  "occupational liver damage -- beta-propiolactone",
  "occupational liver damage -- bipyridyl pesticides",
  "occupational liver damage -- bismuth",
  "occupational liver damage -- boron",
  "occupational liver damage -- boron hydrides",
  "occupational liver damage -- bromide",
  "occupational liver damage -- cadmium",
  "occupational liver damage -- carbolic acids and anhydrides",
  "occupational liver damage -- carbon disulfide",
  "occupational liver damage -- carbon tetrachloride",
  "occupational liver damage -- carbonyls (metal)",
  "occupational liver damage -- chlorinated benzenes",
  "occupational liver damage -- chlorinated naphthalenes",
  "occupational liver damage -- chlorodiphenyls and derivatives",
  "occupational liver damage -- chloroform",
  "occupational liver damage -- chloroprene",
  "occupational liver damage -- chromium",
  "occupational liver damage -- copper",
  "occupational liver damage -- cresol",
  "occupational liver damage -- cyclopropane",
  "occupational liver damage -- dibromochloropropane",
  "occupational liver damage -- dimethyl sulfate",
  "occupational liver damage -- dimethylnitrosamine",
  "occupational liver damage -- dinitrobenzene",
  "occupational liver damage -- dinitrophenol",
  "occupational liver damage -- dinitrotoluene",
  "occupational liver damage -- diphenyl",
  "occupational liver damage -- ethanolamines",
  "occupational liver damage -- ethyl acetate",
  "occupational liver damage -- ethyl alcohol",
  "occupational liver damage -- ethyl ether",
  "occupational liver damage -- ethyl salicylate",
  "occupational liver damage -- ethylene chlorohydrin",
  "occupational liver damage -- ethylene dibromide",
  "occupational liver damage -- ethylene dichloride",
  "occupational liver damage -- ethylene oxide",
  "occupational liver damage -- ethylenediamine",
  "occupational liver damage -- germanium",
  "occupational liver damage -- hydrazine and derivatives",
  "occupational liver damage -- hydrogen bromides",
  "occupational liver damage -- hydrogen cyanide",
  "occupational liver damage -- ionizing radiation",
  "occupational liver damage -- iron",
  "occupational liver damage -- isopropyl acetate",
  "occupational liver damage -- kepone pesticides",
  "occupational liver damage -- mercaptans",
  "occupational liver damage -- methyl acetate",
  "occupational liver damage -- methyl bromide",
  "occupational liver damage -- methyl chloride",
  "occupational liver damage -- methylene chloride",
  "occupational liver damage -- methylene dianiline",
  "occupational liver damage -- n,n-dimethylformamide",
  "occupational liver damage -- n-butyl acetate",
  "occupational liver damage -- n-heptane",
  "occupational liver damage -- n-n-dimethylacetamide",
  "occupational liver damage -- n-nitrosodimethylamine",
  "occupational liver damage -- n-propyl acetate",
  "occupational liver damage -- naphthalene",
  "occupational liver damage -- naphthol",
  "occupational liver damage -- nickel",
  "occupational liver damage -- nitriles",
  "occupational liver damage -- nitrobenzene",
  "occupational liver damage -- nitromethane",
  "occupational liver damage -- nitroparaffins",
  "occupational liver damage -- nitrophenol",
  "occupational liver damage -- phenol",
  "occupational liver damage -- phosphine",
  "occupational liver damage -- phosphorus",
  "occupational liver damage -- phthalic anhydride",
  "occupational liver damage -- picric acid",
  "occupational liver damage -- polybrominated biphenyls",
  "occupational liver damage -- polychlorinated biphenyls",
  "occupational liver damage -- propylene dichloride",
  "occupational liver damage -- pyridine",
  "occupational liver damage -- pyrogallol",
  "occupational liver damage -- selenium",
  "occupational liver damage -- stibine",
  "occupational liver damage -- styrene/ethyl benzene",
  "occupational liver damage -- tetrachloroethane",
  "occupational liver damage -- tetrachloroethylene",
  "occupational liver damage -- tetramethylthiuram disulfide",
  "occupational liver damage -- tetryl",
  "occupational liver damage -- thallium",
  "occupational liver damage -- thallium sulfate pesticides",
  "occupational liver damage -- thorium dioxide",
  "occupational liver damage -- tin",
  "occupational liver damage -- toluene",
  "occupational liver damage -- trichloroethylene",
  "occupational liver damage -- trinitrotoluene",
  "occupational liver damage -- turpentine",
  "occupational liver damage -- uranium",
  "occupational liver damage -- vinyl chloride",
  "occupational liver damage -- whole body vibration",
  "occupational liver damage -- xylene",
  "occupational metal-induced liver damage -- boron",
  "occupational metal-induced liver damage -- cadmium",
  "occupational metal-induced liver damage -- cobalt",
  "occupational metal-induced liver damage -- copper",
  "occupational metal-induced liver damage -- gold",
  "occupational metal-induced liver damage -- mercury",
  "ocular histoplasmosis syndrome",
  "ocular melanoma",
  "oesophagostomiasis",
  "omphalomesenteric cyst",
  "oncocytoma, renal",
  "open-angle glaucoma",
  "opisthorchiasis",
  "oral cancer",
  "orbital lymphangioma",
  "osteochondroma",
  "osteoma",
  "osteopathia striata, cranial sclerosis",
  "osteopetrosis autosomal dominant type 1",
  "osteopetrosis autosomal dominant type 2",
  "osteopoikilosis",
  "osteoporosis",
  "otosclerosis",
  "ovarian cancer",
  "ovarian carcinosarcoma",
  "ovarian cysts",
  "ovarian germ cell malignant tumor",
  "ovarian germ cell tumor",
  "ovarian low malignant potential tumor",
  "ovarian remnant syndrome",
  "paget's disease of bone",
  "paget's disease, type 1",
  "paget's disease, type 4",
  "pancreas agenesis, dorsal",
  "pancreatic cancer",
  "pancreatic cancer, adult",
  "pancreatic carcinoma, familial",
  "pancreatic islet cell tumors (non-functioning tumor)",
  "pancreatoblastoma",
  "paragonimiases -- lung infection",
  "paragonimiasis",
  "paranasal sinus cancer, adult",
  "paris i dysfibrinogenemia",
  "paris ii dysfibrinogenemia",
  "paroxysmal ventricular fibrillation",
  "partial agenesis of corpus callosum",
  "partial atrioventricular canal",
  "patent ductus arteriosus",
  "pelvic inflammatory disease",
  "penile candidiasis",
  "periosteal chondrosarcoma",
  "peripheral neuroectodermal tumor",
  "pernicious anemia",
  "phyllodes tumor of the prostate",
  "pili annulati",
  "pinworm",
  "pituitary tumors, adult",
  "placental-site gestational trophoblastic tumor",
  "plant toxin-induced liver damage -- albitocin",
  "plant toxin-induced liver damage -- cycasin",
  "plant toxin-induced liver damage -- icterogenin",
  "plant toxin-induced liver damage -- indospicine",
  "plant toxin-induced liver damage -- lanthana",
  "plant toxin-induced liver damage -- ngaione",
  "plant toxin-induced liver damage -- nutmeg",
  "plant toxin-induced liver damage -- pyrrolidizine",
  "plant toxin-induced liver damage -- safrole",
  "plant toxin-induced liver damage -- tannic acid",
  "pleuropulmonary blastoma",
  "plexosarcoma",
  "pneumoconiosis",
  "polycystic kidney disease",
  "polycystic liver disease",
  "polycythemia",
  "polycythemia vera",
  "polyhydramnios",
  "polyomavirus allograft nephropathy",
  "polyomavirus infections",
  "posterior vitreous detachment",
  "posthemorrhagic anemia",
  "potassium deficiency",
  "pregnancy toxemia /hypertension",
  "prekallikrein deficiency, congenital",
  "primary aldosteronism",
  "primary autoimmune hemolytic anemia",
  "primary chondrosarcoma",
  "primary ciliary dyskinesia",
  "primary ciliary dyskinesia, 10",
  "primary ciliary dyskinesia, 11",
  "primary ciliary dyskinesia, 12",
  "primary ciliary dyskinesia, 2",
  "primary ciliary dyskinesia, 3",
  "primary ciliary dyskinesia, 4",
  "primary ciliary dyskinesia, 5",
  "primary ciliary dyskinesia, 6",
  "primary ciliary dyskinesia, 7",
  "primary ciliary dyskinesia, 8",
  "primary ciliary dyskinesia, 9",
  "primary cold autoimmune hemolytic anemia",
  "primary cortisol resistance",
  "primary fallopian tube cancer",
  "primary glaucoma associated with ocular abnormalities",
  "primary granulocytic sarcoma",
  "primary immunodeficiency disorders",
  "primary pulmonary hypertension",
  "primary pulmonary hypertension -- dexfenfluramine-associated",
  "primary pulmonary hypertension -- fenfluramine-associated",
  "primary sclerosing cholangitis",
  "prostate cancer",
  "prostate cancer, familial",
  "prostate cancer, hereditary, 1",
  "prostate cancer, hereditary, 10",
  "prostate cancer, hereditary, 11",
  "prostate cancer, hereditary, 12",
  "prostate cancer, hereditary, 13",
  "prostate cancer, hereditary, 14",
  "prostate cancer, hereditary, 15",
  "prostate cancer, hereditary, 2",
  "prostate cancer, hereditary, 3",
  "prostate cancer, hereditary, 4",
  "prostate cancer, hereditary, 5",
  "prostate cancer, hereditary, 6",
  "prostate cancer, hereditary, 7",
  "prostate cancer, hereditary, 8",
  "prostate cancer, hereditary, 9",
  "prostate cancer, hereditary, x-linked 2",
  "protein r deficiency",
  "proteinuria",
  "prurigo",
  "pseudoarylsulfatase a deficiency",
  "psychotropic agent-induced liver damage",
  "psychotropic agent-induced liver damage -- benzodiazepine",
  "psychotropic agent-induced liver damage -- butyrophenone",
  "psychotropic agent-induced liver damage -- monoamine oxidase inhibitors",
  "psychotropic agent-induced liver damage -- phenothiazines",
  "psychotropic agent-induced liver damage -- thioxanthene",
  "psychotropic agent-induced liver damage -- tricyclic antidepressant",
  "pulmonary alveolar microlithiasis",
  "pulmonary alveolar proteinosis",
  "pulmonary arterio-veinous aneurysm",
  "pulmonary arteriovenous fistula",
  "pulmonary arteriovenous malformation",
  "pulmonary artery agenesis",
  "pulmonary artery, isolated unilateral absence of (isolated uapa)",
  "pulmonary branches stenosis",
  "pulmonary hypertension",
  "pulmonary hypoxic hypertension",
  "pulmonary nodular lymphoid hyperplasia, familial",
  "pulmonary pseudolymphoma",
  "pulmonary sequestration",
  "pulmonary thromboembolic hypertension",
  "pulmonary valve stenosis",
  "pyle disease",
  "pyridoxine deficiency-induced sideroblastic anemia",
  "q fever",
  "rectosigmoid neoplasm",
  "renal adysplasia dominant type",
  "renal artery stenosis",
  "renal cancer",
  "renal cell carcinoma associated with neuroblastoma",
  "renal glucosuria",
  "renal glycosuria",
  "renal hypouricemia",
  "renal osteodystrophy",
  "renal pelvis and ureter, transitional cell cancer",
  "renal tuberculosis",
  "reovirus infection",
  "respiratory depression",
  "retinopathy",
  "retroperitoneal liposarcoma",
  "rhabditida infections",
  "rhabdoid tumor",
  "rhabdomyosarcoma 1",
  "rhabdomyosarcoma of the orbit",
  "rhabdomyosarcoma, alveolar",
  "rhabdomyosarcoma, botryoid type",
  "rhabdomyosarcoma, embryonal",
  "rhabdomyosarcoma, embryonal 1",
  "rhabdomyosarcoma, embryonal 2",
  "ribbing disease",
  "ribbing syndrome",
  "rift valley fever",
  "right ventricle hypoplasia",
  "saint louis dysfibrinogenemia",
  "salivary gland cancer, adult",
  "salmonella typhimurium infection",
  "sarcoid",
  "sarcoidosis",
  "sarcosinemia",
  "sarcosporidiosis",
  "sbcad deficiency",
  "schistosomiasis",
  "sclerosing mesenteritis",
  "secernentea infections",
  "secondary autoimmune hemolytic anemia",
  "secondary causes of glaucoma",
  "secondary chondrosarcoma",
  "secondary cold autoimmune hemolytic anemia",
  "secondary fallopian tube cancer",
  "secondary hyperparathyroidism",
  "secondary pulmonary hypertension",
  "selective iga deficiency",
  "selective vitamin b12 malabsorption with proteinuria",
  "serratia urinary tract infection",
  "sertoli-leydig cell tumors",
  "sexually transmitted diseases",
  "shallow breathing",
  "shigellosis",
  "short qt syndrome",
  "short qt syndrome 1",
  "short qt syndrome 2",
  "short qt syndrome 3",
  "short qt syndrome, familial",
  "sickle cell anemia",
  "sideroblastic anemia",
  "sideropenic anemia",
  "silent conditions",
  "silent sinus syndrome",
  "silicosis",
  "silo unloader syndrome",
  "simple kidney cysts",
  "sino-auricular heart block",
  "sinus bradycardia",
  "sinus cancer",
  "sinus node disease",
  "sinus tachycardia",
  "small intestine cancer",
  "small intestine cancer, adult",
  "smith disease",
  "spinal avm",
  "spinal cord neoplasm",
  "spleen neoplasm",
  "splenic infarct",
  "splenic infarcts",
  "splenomegaly",
  "st. louis encephalitis",
  "steatocystoma multiplex",
  "steatocystoma multiplex -- natal teeth",
  "stomach cancer",
  "stomach cancer, familial",
  "stones",
  "streptococcal group a invasive disease",
  "streptococcal group b invasive disease",
  "stress-induced hypertension",
  "strongyloidiasis",
  "subependymal nodular heterotopia",
  "subependymoma",
  "subpulmonary stenosis",
  "sudden arrhythmia death syndrome",
  "supraglottic laryngeal cancer",
  "supravalvular aortic stenosis",
  "synovial cancer",
  "synovial osteochondromatosis",
  "syphilis",
  "syphilis, latent",
  "syringomelia",
  "t-lymphocytopenia",
  "takahara syndrome",
  "tapeworms",
  "tarlov cysts",
  "tethered spinal cord syndrome",
  "thalassemia minima",
  "thallessemia",
  "thrombasthenia",
  "thrombocythemia",
  "thrombosis",
  "thymic epithelial tumor",
  "thyroglossal tract cyst",
  "thyroid cancer, follicular",
  "thyroid cancer, hurthle cell",
  "thyroid cancer, medullary",
  "thyroid cancer, papillary",
  "togaviridae disease",
  "torch syndrome",
  "torulopsis",
  "toxin-induced sideroblastic anemia",
  "toxocariasis",
  "toxoplasmosis",
  "transcobalamin i deficiency",
  "transitional cell carcinoma",
  "treponema infection",
  "trichinosis",
  "trichomoniasis",
  "tricuspid valve disease",
  "triple-x syndrome",
  "trisomy 10 mosaicism",
  "trisomy 11 mosaicism",
  "trisomy 12 mosaicism",
  "trisomy 13 mosaicism",
  "trisomy 18 mosaicism",
  "trisomy 19 mosaicism",
  "trisomy 2 mosaicism",
  "trisomy 20 mosaicism",
  "trisomy 21 mosaicism",
  "trisomy 22 mosaicism",
  "trisomy 3 mosaicism",
  "trisomy 4 mosaicism",
  "trisomy 5 mosaicism",
  "trisomy 6 mosaicism",
  "trisomy 7 mosaicism",
  "trisomy 8 mosaicism",
  "troyes dysfibrinogenemia",
  "tuberculosis",
  "tuberculosis, pulmonary",
  "tuberous sclerosis",
  "type 2 diabetes",
  "type i hyperlipoproteinemia",
  "type ia hyperlipoproteinemia",
  "type ib hyperlipoproteinemia",
  "type ic hyperlipoproteinemia",
  "type ii hyperlipoproteinemia",
  "type iia hyperlipoproteinemia",
  "type iib hyperlipoproteinemia",
  "type iii hyperlipoproteinemia",
  "type iv hyperlipoproteinemia",
  "typhoid fever",
  "unilateral pulmonary agenesis",
  "upd10",
  "upd2",
  "upd5",
  "urachal cancer",
  "urethral cancer",
  "urinary tract infections",
  "urinary tract neoplasm",
  "uterine fibroids",
  "uterine prolapse",
  "uterine sarcoma",
  "vagal paraganglioma",
  "vagina cancer",
  "vaginitis",
  "vaginosis (bacterial vaginosis)",
  "valvular dysplasia of the child",
  "vascular malformations of the brain",
  "venous thrombosis",
  "ventricular fibrillation, paroxysmal familial, 1",
  "ventricular fibrillation, paroxysmal familial, 2",
  "ventricular septal defect",
  "very long chain acyl coa dehydrogenase deficiency -- adult-onset",
  "very long chain acyl coa dehydrogenase deficiency -- intermediate",
  "viral hepatitis",
  "viremia",
  "virilizing ovarian tumor",
  "vitamin b12 deficiency",
  "vitelliform macular dystrophy -- adult-onset",
  "vitreous detachment",
  "vulvar cancer",
  "vulvar neoplasms",
  "warm autoimmune hemolytic anemia",
  "warm-reacting-antibody hemolytic anemia",
  "warthin's tumor",
  "weil's syndrome",
  "western equine encephalitis",
  "whipworm",
  "wilms tumor 2",
  "wilms tumor 3",
  "wilms tumor 4",
  "wilms tumor and radial bilateral aplasia",
  "wolf-parkinson-white syndrome",
  "wuchereria bancrofti",
  "xanthine oxidase deficiency type i",
  "xanthine oxidase deficiency type ii",
  "zurich i dysfibrinogenemia",
  "zurich ii dysfibrinogenemia",
];