symptoms = {
    "abdominal pain": {
        "causes": [
            "abdominal aortic aneurysm", 
            "appendicitis", 
            "cholangitis (bile duct inflammation)", 
            "cholecystitis (gallbladder inflammation)", 
            "cystitis (bladder inflammation)", 
            "diabetic ketoacidosis (high levels of ketones in the blood)", 
            "diverticulitis", 
            "duodenitis (inflammation of the initial portion of the small intestine)", 
            "ectopic pregnancy", 
            "fecal impaction (hardened stool that can't be eliminated)", 
            "heart attack", 
            "injury", 
            "intussusception (in children)", 
            "kidney infection", 
            "kidney stones", 
            "liver abscess (pus-filled pocket in the liver)", 
            "mesenteric ischemia (decreased blood flow to the intestines)", 
            "mesenteric lymphadenitis (swollen lymph nodes in the folds of membrane that hold the abdominal organs in place)", 
            "mesenteric thrombosis (blood clot in a vein carrying blood away from your intestines)", 
            "pancreatitis (pancreas inflammation)", 
            "pericarditis (inflammation of the tissue around the heart)", 
            "peritonitis (infection of the abdominal lining)", 
            "pleurisy (inflammation of the membrane surrounding the lungs)", 
            "pneumonia", 
            "pulmonary infarction (loss of blood flow to the lungs)", 
            "ruptured spleen", 
            "salpingitis (inflammation of the fallopian tubes)", 
            "shingles", 
            "spleen infection", 
            "splenic abscess (pus-filled pocket in the spleen)", 
            "torn colon", 
            "urinary tract infection (uti)", 
            "viral gastroenteritis (stomach flu)", 
            "angina (reduced blood flow to the heart)", 
            "celiac disease", 
            "endometriosis", 
            "gallstones", 
            "gastritis (inflammation of the stomach lining)", 
            "gerd (gastroesophageal reflux disease)", 
            "hiatal hernia", 
            "inguinal hernia", 
            "mittelschmerz (pain associated with ovulation)", 
            "nonulcer stomach pain", 
            "ovarian cysts", 
            "pelvic inflammatory disease (pid) - infection of the female reproductive organs", 
            "peptic ulcer", 
            "sickle cell anemia", 
            "strained or pulled abdominal muscle", 
            "ulcerative colitis", 
            "cancer", 
            "crohn's disease", 
            "enlarged spleen (splenomegaly)", 
            "gallbladder cancer", 
            "hepatitis (liver inflammation)", 
            "kidney cancer", 
            "lead poisoning", 
            "liver cancer", 
            "non-hodgkin's lymphoma", 
            "pancreatic cancer", 
            "stomach cancer", 
            "tubo-ovarian abscess (pus-filled pocket involving a fallopian tube and an ovary)", 
            "uremia (buildup of waste products in your blood)"
        ], 
        "url": "http://www.mayoclinic.org/symptoms/abdominal-pain/basics/definition/sym-20050728"
    }, 
    "anal pain": {
        "causes": [
            "anal cancer", 
            "anal fissure (a small tear in the lining of the anal canal)", 
            "anal itching (pruritus ani)", 
            "anal sex", 
            "anorectal fistula (an abnormal channel between the anus or rectum usually to the skin near the anus)", 
            "coccydynia or coccygodynia (tailbone pain)", 
            "chronic constipation", 
            "crohn's disease (a type of inflammatory bowel disease)", 
            "diarrhea (causing anal irritation)", 
            "fecal impaction (a mass of hardened stool in the rectum due to chronic constipation)", 
            "hemorrhoids (swollen and inflamed veins in your anus or rectum)", 
            "levator ani syndrome (spasm in the muscles that surround the anus)", 
            "perianal abscess (pus in the deep tissue around the anus)", 
            "perianal hematoma (a collection of blood in the perianal tissue caused by a ruptured vein, sometimes called an external hemorrhoid)", 
            "proctalgia fugax (fleeting pain due to rectal muscle spasm)", 
            "proctitis (inflammation of the lining of the rectum)", 
            "solitary rectal ulcer syndrome (ulcer of the rectum)", 
            "thrombosed hemorrhoid (blood clot in a hemorrhoid)", 
            "trauma", 
            "ulcerative colitis (a type of inflammatory bowel disease)", 
            "ulcerative proctitis (a type of inflammatory bowel disease)"
        ], 
        "url": "http://www.mayoclinic.org/symptoms/anal-pain/basics/definition/sym-20050918"
    }, 
    "ankle pain": {
        "causes": [
            "achilles tendinitis", 
            "achilles tendon rupture", 
            "avulsion fracture", 
            "broken ankle/broken foot", 
            "bursitis", 
            "gout", 
            "osteoarthritis", 
            "osteochondritis dissecans", 
            "plantar fasciitis", 
            "pseudogout", 
            "psoriatic arthritis", 
            "reactive arthritis", 
            "rheumatoid arthritis", 
            "septic arthritis", 
            "sprained ankle", 
            "stress fractures", 
            "tarsal tunnel syndrome"
        ], 
        "url": "http://www.mayoclinic.org/symptoms/ankle-pain/basics/definition/sym-20050796"
    }, 
    "arm pain": {
        "causes": [
            "angina", 
            "brachial plexus injury", 
            "broken arm", 
            "broken wrist/broken hand", 
            "bursitis", 
            "carpal tunnel syndrome", 
            "cervical disk herniation", 
            "de quervain's tenosynovitis", 
            "dislocated elbow", 
            "meralgia paresthetica", 
            "hiatal hernia", 
            "pinched nerve", 
            "rheumatoid arthritis", 
            "rotator cuff injury", 
            "sprains and strains", 
            "tendinitis", 
            "tennis elbow", 
            "thoracic outlet syndrome"
        ], 
        "url": "http://www.mayoclinic.org/symptoms/arm-pain/basics/definition/sym-20050870"
    }, 
    "back pain": {
        "causes": [
            "ankylosing spondylitis", 
            "meralgia paresthetica", 
            "herniated disk", 
            "kidney infection", 
            "obesity", 
            "osteoarthritis", 
            "osteomyelitis", 
            "osteoporosis", 
            "paget's disease of bone", 
            "poor posture", 
            "pregnancy", 
            "rheumatoid arthritis", 
            "sacroiliitis", 
            "sciatica", 
            "scoliosis", 
            "spinal fractures", 
            "spinal stenosis"
        ], 
        "url": "http://www.mayoclinic.org/symptoms/back-pain/basics/definition/sym-20050878"
    }, 
    "bent penis": {
        "causes": [
            "normal differences in penis anatomy", 
            "autoimmune disorder", 
            "inherited fibrous tissue (collagen) abnormality", 
            "injury to the penis", 
            "peyronie's disease (a curved erection caused by one of a number of underlying conditions)"
        ], 
        "url": "http://www.mayoclinic.org/symptoms/bent-penis/basics/definition/sym-20050628"
    }, 
    "bleeding during pregnancy": {
        "causes": [
            "- the spontaneous loss of pregnancy before the 20th week", 
            "implantation bleeding - which occurs about 10 to 14 days after conception", 
            "ectopic pregnancy", 
            "molar pregnancy - a rare occurrence in which an abnormal mass - instead of a baby - forms inside the uterus after fertilization", 
            "(before the 20th week) or intrauterine fetal death", 
            "placental abruption", 
            "cervicitis", 
            "incompetent cervix - premature opening of the cervix - which can lead to preterm birth", 
            "problems with the cervix, such as a cervical infection, inflamed cervix or growths on the cervix", 
            "preterm labor - which might result in light bleeding - especially when accompanied by contractions, dull backache or pelvic pressure", 
            "uterine rupture, a rare but life-threatening occurrence in which the uterus tears open along the scar line from a prior c-section"
        ], 
        "url": "http://www.mayoclinic.org/symptoms/bleeding-during-pregnancy/basics/definition/sym-20050636"
    }, 
    "blood clots": {
        "causes": [
            "antiphospholipid syndrome", 
            "arteriosclerosis / atherosclerosis", 
            "certain medications, such as oral contraceptives, hormone therapy drugs and some breast cancer medications", 
            "deep vein thrombosis (dvt)", 
            "factor v leiden", 
            "family history of blood clots", 
            "heart arrhythmias", 
            "hiatal hernia", 
            "heart failure", 
            "obesity", 
            "peripheral artery disease", 
            "polycythemia vera", 
            "pregnancy", 
            "prolonged sitting or bed rest", 
            "pulmonary embolism (blood clot in an artery in the lung)", 
            "smoking", 
            "stroke", 
            "surgery"
        ], 
        "url": "http://www.mayoclinic.org/symptoms/blood-clots/basics/definition/sym-20050850"
    }, 
    "blood in semen": {
        "causes": [
            "brachytherapy", 
            "chlamydia", 
            "epididymitis", 
            "excessive sexual activity or masturbation", 
            "external beam radiation for prostate cancer", 
            "genital herpes", 
            "forgotten (retained) tampon", 
            "hemophilia", 
            "interrupted sex", 
            "orchitis", 
            "prolonged sexual abstinence", 
            "prostate biopsy", 
            "prostate cancer", 
            "prostatitis", 
            "testicular trauma", 
            "vasectomy", 
            "amyloidosis", 
            "benign growths (cysts, polyps) in the bladder, urethra or prostate", 
            "schistosomiasis", 
            "testicular cancer", 
            "tuberculosis", 
            "warfarin side effects"
        ], 
        "url": "http://www.mayoclinic.org/symptoms/blood-in-semen/basics/definition/sym-20050603"
    }, 
    "brain lesions": {
        "causes": [
            "brain aneurysm", 
            "brain avm (arteriovenous malformation)", 
            "brain tumor (both cancerous and noncancerous)", 
            "encephalitis", 
            "hydrocephalus (a congenital brain abnormality)", 
            "multiple sclerosis", 
            "traumatic brain injury"
        ], 
        "url": "http://www.mayoclinic.org/symptoms/brain-lesions/basics/definition/sym-20050692"
    }, 
    "breast calcifications": {
        "causes": [
            "breast cancer", 
            "breast cysts", 
            "fibroadenoma - a solid, benign mass most common in young women", 
            "cell secretions or debris", 
            "ductal carcinoma in situ (dcis)", 
            "mammary duct ectasia", 
            "previous injury or surgery to the breast (fat necrosis)", 
            "previous radiation therapy for cancer", 
            "skin (dermal) or blood vessel (vascular) calcification"
        ], 
        "url": "http://www.mayoclinic.org/symptoms/breast-calcifications/basics/definition/sym-20050834"
    }, 
    "breast lumps": {
        "causes": [
            "breast cancer", 
            "breast cysts - fluid-filled sacs in your breast that are usually benign", 
            "fibroadenoma - a solid, benign mass most common in young women", 
            "fibrocystic breasts", 
            "injury or trauma to the breast", 
            "intraductal papilloma - a benign, wartlike growth in a milk duct", 
            "lipoma - a slow-growing, doughy mass that's usually harmless", 
            "mastitis - an infection in breast tissue that most commonly affects women who are breast-feeding", 
            "milk cyst (galactocele) - a milk-filled cyst that's usually harmless"
        ], 
        "url": "http://www.mayoclinic.org/symptoms/breast-lumps/basics/definition/sym-20050619"
    }, 
    "breast rash": {
        "causes": [
            "breast abscess", 
            "inflammatory breast cancer", 
            "mammary duct ectasia", 
            "mastitis - an infection in breast tissue that most commonly affects women who are breast-feeding", 
            "nipple dermatitis", 
            "nipple piercings or other body art, such as tattooing", 
            "paget's disease of the breast", 
            "radiation dermatitis", 
            "atopic dermatitis (eczema)", 
            "candidiasis (especially under the breasts)", 
            "cellulitis (a skin infection)", 
            "dermatitis", 
            "hives and angioedema", 
            "psoriasis", 
            "scabies", 
            "seborrheic dermatitis"
        ], 
        "url": "http://www.mayoclinic.org/symptoms/breast-rash/basics/definition/sym-20050817"
    }, 
    "burning feet": {
        "causes": [
            "alcohol use disorder", 
            "athlete's foot", 
            "charcot-marie-tooth disease (a group of hereditary disorders that affects the nerves in your arms and legs)", 
            "chemotherapy", 
            "chronic kidney disease", 
            "complex regional pain syndrome (chronic pain due to a dysfunctional nervous system)", 
            "diabetic neuropathy (diabetes-related nerve damage)", 
            "hiv/aids", 
            "hypothyroidism (underactive thyroid)", 
            "tarsal tunnel syndrome", 
            "vitamin deficiency anemia"
        ], 
        "url": "http://www.mayoclinic.org/symptoms/burning-feet/basics/definition/sym-20050809"
    }, 
    "cold hands": {
        "causes": [
            "anemia", 
            "buerger's disease", 
            "diabetes", 
            "frostbite", 
            "lupus", 
            "raynaud's disease", 
            "scleroderma"
        ], 
        "url": "http://www.mayoclinic.org/symptoms/cold-hands/basics/definition/sym-20050648"
    }, 
    "cough": {
        "causes": [
            "common cold", 
            "influenza (flu)", 
            "inhaling an irritant", 
            "strained or pulled abdominal muscle", 
            "whooping cough", 
            "allergies", 
            "asthma (most common in children)", 
            "bronchitis", 
            "gerd (gastroesophageal reflux disease)", 
            "postnasal drip", 
            "acute sinusitis", 
            "bronchiectasis", 
            "bronchiolitis (especially in young children)", 
            "choking: first aid (especially in children)", 
            "chronic sinusitis", 
            "copd", 
            "croup (especially in young children)", 
            "cystic fibrosis", 
            "emphysema", 
            "heart failure", 
            "laryngitis", 
            "lung cancer", 
            "medications called angiotensin-converting enzyme (ace) inhibitors", 
            "neuromuscular diseases, such as parkinsonism, which weaken the coordination of upper airway and swallowing muscles", 
            "respiratory syncytial virus (rsv) (especially in young children)", 
            "tuberculosis"
        ], 
        "url": "http://www.mayoclinic.org/symptoms/cough/basics/definition/sym-20050846"
    }, 
    "coughing up blood": {
        "causes": [
            "copd (chronic obstructive pulmonary disease) and other lung diseases", 
            "cystic fibrosis", 
            "drug use, such as crack cocaine", 
            "foreign body", 
            "granulomatosis with polyangiitis (wegener's granulomatosis)", 
            "lung abscess", 
            "lung cancer", 
            "emphysema", 
            "mitral valve stenosis", 
            "parasitic infection", 
            "strained or pulled abdominal muscle", 
            "pulmonary embolism (blood clot in an artery in the lung)", 
            "trauma to the chest", 
            "tuberculosis"
        ], 
        "url": "http://www.mayoclinic.org/symptoms/coughing-up-blood/basics/definition/sym-20050934"
    }, 
    "dark circles under eyes": {
        "causes": [
            "allergies", 
            "atopic dermatitis (eczema)", 
            "contact dermatitis", 
            "fatigue", 
            "hay fever (allergic rhinitis)", 
            "heredity - dark under-eye circles can run in families", 
            "pigmentation irregularities - these are a particular concern for people of color, especially blacks and asians", 
            "rubbing or scratching your eyes", 
            "sun exposure, which prompts your body to produce more melanin, the pigment that gives skin its color", 
            "thinning skin and loss of fat and collagen - common as you age - can make the reddish-blue blood vessels under your eyes more obvious"
        ], 
        "url": "http://www.mayoclinic.org/symptoms/dark-circles-under-eyes/basics/definition/sym-20050624"
    }, 
    "diarrhea": {
        "causes": [
            "antibiotic-associated diarrhea", 
            "c. difficile infection", 
            "cryptosporidium infection", 
            "cytomegalovirus (cmv) infection", 
            "e. coli", 
            "food intolerances", 
            "food poisoning", 
            "fructose intolerance", 
            "artificial sweeteners", 
            "giardiasis (giardia infection)", 
            "lactose intolerance", 
            "norovirus infection", 
            "medicines, such as antacids containing magnesium and some cancer treatments", 
            "rotavirus", 
            "salmonella infection", 
            "shigella infection", 
            "stomach surgery", 
            "traveler's diarrhea", 
            "celiac disease", 
            "colon cancer", 
            "cholecystitis (gallbladder inflammation)", 
            "inflammatory bowel disease (ibd)", 
            "duodenitis (inflammation of the initial portion of the small intestine)", 
            "medications used to treat heartburn, such as proton pump inhibitors and h2 receptor antagonists", 
            "ulcerative colitis", 
            "whipple's disease"
        ], 
        "url": "http://www.mayoclinic.org/symptoms/diarrhea/basics/definition/sym-20050926"
    }, 
    "dizziness": {
        "causes": [
            "benign paroxysmal positional vertigo (bppv)", 
            "ear infection (middle ear)", 
            "meniere's disease", 
            "migraine", 
            "arteriosclerosis / atherosclerosis", 
            "congenital heart disease in adults", 
            "heart arrhythmias", 
            "orthostatic hypotension (postural hypotension)", 
            "stroke", 
            "transient ischemic attack (tia)", 
            "antidepressants", 
            "anti-seizure drugs", 
            "drugs to control high blood pressure", 
            "sedatives", 
            "tranquilizers", 
            "anemia", 
            "concussion", 
            "generalized anxiety disorder", 
            "hypoglycemia", 
            "motion sickness: first aid", 
            "panic attacks and panic disorder"
        ], 
        "url": "http://www.mayoclinic.org/symptoms/dizziness/basics/definition/sym-20050886"
    }, 
    "dry orgasm": {
        "causes": [
            "cystectomy (bladder removal surgery)", 
            "blocked sperm duct (ejaculatory duct obstruction)", 
            "certain medications used to treat high blood pressure, enlarged prostate and mood disorders", 
            "diabetes", 
            "genetic abnormalities of the reproductive system", 
            "male hypogonadism (testosterone deficiency)", 
            "multiple sclerosis", 
            "prostatectomy", 
            "anterior prolapse (cystocele)", 
            "holmium laser prostate surgery", 
            "radiation therapy", 
            "retrograde ejaculation", 
            "spinal cord injury", 
            "tuip", 
            "tumt", 
            "turp"
        ], 
        "url": "http://www.mayoclinic.org/symptoms/dry-orgasm/basics/definition/sym-20050906"
    }, 
    "elbow pain": {
        "causes": [
            "broken arm", 
            "bursitis", 
            "dislocated elbow", 
            "golfer's elbow", 
            "osteoarthritis", 
            "osteochondritis dissecans", 
            "rheumatoid arthritis", 
            "sprains and strains", 
            "stress fractures", 
            "tendinitis", 
            "tennis elbow", 
            "throwing injuries", 
            "trapped nerves"
        ], 
        "url": "http://www.mayoclinic.org/symptoms/elbow-pain/basics/definition/sym-20050874"
    }, 
    "elevated liver enzymes": {
        "causes": [
            "certain prescription medications, including statin drugs used to control cholesterol", 
            "drinking alcohol", 
            "heart failure", 
            "hepatitis a", 
            "hepatitis b", 
            "hepatitis c", 
            "nonalcoholic fatty liver disease", 
            "obesity", 
            "over-the-counter pain medications, particularly acetaminophen (tylenol, others)", 
            "alcoholic hepatitis (severe liver inflammation caused by excessive  alcohol consumption)", 
            "autoimmune hepatitis (liver inflammation caused by an autoimmune disorder)", 
            "celiac disease (small intestine damage caused by gluten)", 
            "cirrhosis (early stages of liver scarring)", 
            "cytomegalovirus (cmv) infection", 
            "dermatomyositis (inflammatory disease that causes muscle weakness and skin rash)", 
            "epstein-barr virus", 
            "gallbladder inflammation (cholecystitis)", 
            "hiatal hernia", 
            "hemochromatosis (too much iron stored in your body)", 
            "hypothyroidism (underactive thyroid)", 
            "liver cancer", 
            "mononucleosis", 
            "pancreatitis (pancreas inflammation)", 
            "polymyositis (inflammatory disease that causes muscle weakness)", 
            "toxic hepatitis (liver inflammation caused by drugs or toxins)", 
            "wilson's disease (too much copper stored in your body)"
        ], 
        "url": "http://www.mayoclinic.org/symptoms/elevated-liver-enzymes/basics/definition/sym-20050830"
    }, 
    "eosinophilia": {
        "causes": [
            "parasitic and fungal diseases", 
            "allergies including allergies to medications or food", 
            "adrenal conditions", 
            "skin disorders", 
            "toxins", 
            "autoimmune diseases", 
            "endocrine disorders", 
            "tumors", 
            "acute myelogenous leukemia (aml)", 
            "ascariasis (a roundworm infection)", 
            "asthma", 
            "atopic dermatitis (eczema)", 
            "cancer", 
            "churg-strauss syndrome", 
            "cholecystitis (gallbladder inflammation)", 
            "drug allergy", 
            "eosinophilic esophagitis", 
            "eosinophilic leukemia", 
            "hay fever", 
            "hodgkin's lymphoma", 
            "hypereosinophilic syndrome", 
            "idiopathic hypereosinophilic syndrome (hes), an extremely high eosinophil count of unknown origin", 
            "lymphatic filariasis (a parasitic infection)", 
            "ovarian cancer", 
            "parasitic infections", 
            "primary immunodeficiency", 
            "trichinosis (a roundworm infection)", 
            "ulcerative colitis"
        ], 
        "url": "http://www.mayoclinic.org/symptoms/eosinophilia/basics/definition/sym-20050752"
    }, 
    "excessive sweating": {
        "causes": [
            "diabetes", 
            "endocarditis", 
            "fever of undetermined cause", 
            "generalized anxiety disorder", 
            "hiatal hernia", 
            "heat exhaustion", 
            "hiv/aids", 
            "hyperhidrosis", 
            "hyperthyroidism (overactive thyroid)", 
            "leukemia", 
            "malaria", 
            "medication side effects, such as sometimes experienced when taking some beta blockers and antidepressants", 
            "menopause", 
            "gastritis (inflammation of the stomach lining)", 
            "obesity", 
            "stress", 
            "tuberculosis"
        ], 
        "url": "http://www.mayoclinic.org/symptoms/excessive-sweating/basics/definition/sym-20050780"
    }, 
    "eye pain": {
        "causes": [
            "allergies", 
            "blepharitis (eyelid inflammation)", 
            "blocked tear duct", 
            "chalazion (a type of cyst on your eyelid)", 
            "cluster headache", 
            "contact lens problem", 
            "corneal abrasion (scratch): first aid", 
            "dry eyes (decreased production of tears)", 
            "ectropion (outwardly turned eyelid)", 
            "entropion (inwardly turned eyelid)", 
            "foreign object in the eye: first aid", 
            "glaucoma (group of conditions that damage the optic nerve)", 
            "injury, such as from a blunt trauma or burn", 
            "iritis (inflammation of the colored part of the eye)", 
            "keratitis (inflammation of the cornea)", 
            "optic neuritis (inflammation of the optic nerve)", 
            "pink eye (conjunctivitis)", 
            "scleritis (inflammation of the white part of the eye)", 
            "sty", 
            "uveitis (inflammation of the middle layer of the eye)"
        ], 
        "url": "http://www.mayoclinic.org/symptoms/eye-pain/basics/definition/sym-20050744"
    }, 
    "eye twitching": {
        "causes": [
            "alcohol intake", 
            "bright light", 
            "caffeine excess", 
            "fatigue", 
            "irritation of the eye surface or inner eyelids", 
            "physical exertion", 
            "smoking", 
            "stress", 
            "wind", 
            "blepharitis", 
            "corneal abrasion", 
            "dry eyes (decreased production of tears)", 
            "entropion", 
            "glaucoma", 
            "light sensitivity", 
            "trichiasis", 
            "uveitis", 
            "bell's palsy", 
            "cervical dystonia", 
            "dystonia", 
            "multiple sclerosis", 
            "oromandibular dystonia and facial dystonia", 
            "tourette syndrome"
        ], 
        "url": "http://www.mayoclinic.org/symptoms/eye-twitching/basics/definition/sym-20050838"
    }, 
    "fatigue": {
        "causes": [
            "use of alcohol or drugs", 
            "excess physical activity", 
            "jet lag", 
            "lack of physical activity", 
            "lack of sleep", 
            "medications, such as antihistamines, cough medicines", 
            "unhealthy eating habits", 
            "acute liver failure", 
            "anemia", 
            "anxiety", 
            "cancer", 
            "chronic fatigue syndrome", 
            "chronic infection or inflammation", 
            "chronic kidney disease", 
            "concussion", 
            "copd", 
            "depression (major depressive disorder)", 
            "diabetes", 
            "emphysema", 
            "meralgia paresthetica", 
            "grief", 
            "heart disease", 
            "hyperthyroidism (overactive thyroid)", 
            "hypothyroidism (underactive thyroid)", 
            "inflammatory bowel disease (ibd)", 
            "medications and treatments, such as chemotherapy, radiation therapy, pain drugs, heart drugs and antidepressants", 
            "multiple sclerosis", 
            "obesity", 
            "pain that's persistent", 
            "sleep apnea", 
            "stress", 
            "traumatic brain injury"
        ], 
        "url": "http://www.mayoclinic.org/symptoms/fatigue/basics/definition/sym-20050894"
    }, 
    "foot pain": {
        "causes": [
            "achilles tendinitis", 
            "achilles tendon rupture", 
            "avulsion fracture: how is it treated?", 
            "bone spurs", 
            "broken ankle/broken foot", 
            "broken toe", 
            "bunions", 
            "bursitis", 
            "corns and calluses", 
            "diabetic neuropathy", 
            "flatfeet", 
            "gout", 
            "haglund's deformity", 
            "hammertoe and mallet toe", 
            "high heels or poorly fitting shoes", 
            "ingrown toenails", 
            "metatarsalgia", 
            "osteoarthritis", 
            "osteomyelitis", 
            "paget's disease of bone", 
            "peripheral neuropathy", 
            "plantar fasciitis", 
            "plantar warts", 
            "psoriatic arthritis", 
            "raynaud's disease", 
            "reactive arthritis", 
            "retrocalcaneal bursitis", 
            "rheumatoid arthritis", 
            "septic arthritis", 
            "stress fractures", 
            "tarsal tunnel syndrome", 
            "tendinitis", 
            "tumors"
        ], 
        "url": "http://www.mayoclinic.org/symptoms/foot-pain/basics/definition/sym-20050792"
    }, 
    "frequent bowel movements": {
        "causes": [], 
        "url": "http://www.mayoclinic.org/symptoms/frequent-bowel-movements/basics/definition/sym-20050720"
    }, 
    "frequent urination": {
        "causes": [
            "infection, disease, injury or irritation of the bladder", 
            "conditions that increase urine production", 
            "changes in muscles, nerves or other tissues affecting bladder function", 
            "certain cancer treatments", 
            "drugs or beverages that increase urine production", 
            "pain or discomfort during urination", 
            "a strong urge to urinate", 
            "difficulty urinating", 
            "loss of bladder control", 
            "unusual urine color", 
            "anterior prolapse (cystocele)", 
            "anxiety", 
            "benign prostatic hyperplasia (bph)", 
            "bladder stones", 
            "change in kidney function", 
            "diabetes insipidus", 
            "diuretics (water retention relievers)", 
            "excess consumption of total fluids, alcohol or caffeine", 
            "interstitial cystitis", 
            "kidney infection", 
            "overactive bladder", 
            "pregnancy", 
            "prostatitis", 
            "radiation treatment affecting the pelvis or lower abdomen", 
            "type 1 diabetes", 
            "type 2 diabetes", 
            "urethral stricture", 
            "urinary incontinence", 
            "salpingitis (inflammation of the fallopian tubes)", 
            "vaginitis"
        ], 
        "url": "http://www.mayoclinic.org/symptoms/frequent-urination/basics/definition/sym-20050712"
    }, 
    "green stool": {
        "causes": [], 
        "url": "http://www.mayoclinic.org/symptoms/green-stool/basics/definition/sym-20050708"
    }, 
    "groin pain (male)": {
        "causes": [
            "avascular necrosis (death of bone tissue due to limited blood flow)", 
            "avulsion fracture: how is it treated? (ligament or tendon pulled from the bone)", 
            "bursitis (joint inflammation)", 
            "epididymitis (testicle inflammation)", 
            "hydrocele (swelling of the scrotum)", 
            "inguinal hernia", 
            "kidney stones", 
            "mumps", 
            "muscle strain", 
            "orchitis (inflamed testicle)", 
            "osteoarthritis", 
            "pinched nerve", 
            "piriformis syndrome", 
            "retractile testicle (testicle that moves between the scrotum and abdomen)", 
            "sciatica", 
            "scrotal masses", 
            "spermatocele (fluid buildup in the testicle)", 
            "stress fractures", 
            "swollen lymph nodes", 
            "tendinitis", 
            "testicular cancer", 
            "testicular torsion (twisted testicle)", 
            "salpingitis (inflammation of the fallopian tubes)", 
            "varicocele (enlarged veins in the scrotum)"
        ], 
        "url": "http://www.mayoclinic.org/symptoms/groin-pain/basics/definition/sym-20050652"
    }, 
    "headache": {
        "causes": [
            "cluster headache", 
            "migraine (with and without aura)", 
            "tension headache (also known as tension-type headache)", 
            "trigeminal autonomic cephalalgia (tac), such as cluster headache and paroxysmal hemicrania", 
            "chronic daily headaches (for example, chronic migraine, chronic tension-type headache, or hemicranias continua)", 
            "cough headaches", 
            "exercise headaches", 
            "sex headaches", 
            "alcohol, particularly red wine", 
            "certain foods, such as processed meats that contain nitrates", 
            "changes in sleep or lack of sleep", 
            "poor posture", 
            "skipped meals", 
            "stress", 
            "acute sinusitis", 
            "arterial tears (carotid or vertebral dissections)", 
            "blood clot (venous thrombosis) within the brain - separate from stroke", 
            "brain aneurysm (a bulge in an artery in your brain)", 
            "brain avm (brain arteriovenous malformation) - an abnormal formation of brain blood vessels", 
            "brain tumor", 
            "carbon monoxide poisoning", 
            "chiari malformation (structural problem at the base of your skull)", 
            "concussion", 
            "dehydration", 
            "dental problems", 
            "ear infection (middle ear)", 
            "encephalitis (brain inflammation)", 
            "giant cell arteritis (inflammation of the lining of the arteries)", 
            "glaucoma (acute angle closure glaucoma)", 
            "hangovers", 
            "high blood pressure (hypertension)", 
            "influenza (flu) and other febrile (fever) illnesses", 
            "intracranial hematoma (blood vessel ruptures with bleeding in or around the brain)", 
            "medications to treat other disorders", 
            "meningitis (inflammation of the membranes and fluid surrounding your brain and spinal cord)", 
            "monosodium glutamate (msg)", 
            "overuse of pain medication", 
            "panic attacks and panic disorder", 
            "post-concussion syndrome", 
            "pressure from tight headgear, such as a helmet or goggles", 
            "pseudotumor cerebri (increased pressure inside the skull), also known as idiopathic intracranial hypertension", 
            "stroke", 
            "toxoplasmosis", 
            "trigeminal neuralgia (as well as other neuralgias, all involving irritation of certain nerves connecting the face and brain)", 
            "external compression headaches (a result of pressure-causing headgear)", 
            "ice cream headaches (commonly called brain freeze)", 
            "rebound headaches (caused by overuse of pain medication)", 
            "sinus headaches (caused by inflammation and congestion in sinus cavities)", 
            "spinal headaches (caused by low pressure or volume of cerebrospinal fluid, possibly the result of spontaneous cerebrospinal fluid leak, spinal tap or spinal anesthesia)", 
            "thunderclap headaches (a group of disorders that involves sudden, severe headaches with multiple causes)"
        ], 
        "url": "http://www.mayoclinic.org/symptoms/headache/basics/definition/sym-20050800"
    }, 
    "heel pain": {
        "causes": [
            "achilles tendinitis", 
            "achilles tendon rupture", 
            "bone tumor", 
            "bursitis", 
            "haglund's deformity", 
            "heel spur", 
            "osteomyelitis", 
            "paget's disease of bone", 
            "peripheral neuropathy", 
            "plantar fasciitis", 
            "reactive arthritis", 
            "retrocalcaneal bursitis", 
            "rheumatoid arthritis", 
            "sarcoidosis", 
            "stress fractures", 
            "tarsal tunnel syndrome"
        ], 
        "url": "http://www.mayoclinic.org/symptoms/heel-pain/basics/definition/sym-20050788"
    }, 
    "high blood protein": {
        "causes": [
            "bone marrow disorder", 
            "multiple myeloma", 
            "amyloidosis", 
            "monoclonal gammopathy of undetermined significance (mgus)", 
            "chronic inflammatory conditions", 
            "hiv/aids", 
            "dehydration (which may make blood proteins appear falsely elevated)"
        ], 
        "url": "http://www.mayoclinic.org/symptoms/high-blood-protein/basics/definition/sym-20050599"
    }, 
    "high hemoglobin count": {
        "causes": [
            "you smoke", 
            "you live at higher altitudes and your red blood cell production naturally increases to compensate for the lower oxygen supply there", 
            "your red blood cell production increases to compensate for chronically low blood oxygen levels due to poor heart or lung function.", 
            "you have a bone marrow dysfunction that results in increased production of red blood cells.", 
            "you've taken drugs or hormones, most commonly erythropoietin (epo), that stimulate red blood cell production. you're not likely to get a high hemoglobin count from epo given to you if you have chronic kidney disease. but epo doping - getting injections to enhance athletic performance - can cause a high hemoglobin count.", 
            "copd (chronic obstructive pulmonary disease) and other lung diseases", 
            "congenital heart disease in adults", 
            "emphysema", 
            "heart failure", 
            "kidney cancer", 
            "liver cancer", 
            "living at a high altitude, where there's less oxygen in the air", 
            "polycythemia vera", 
            "other types of heart disease", 
            "other types of lung disease", 
            "smoking, which may result in low blood oxygen levels"
        ], 
        "url": "http://www.mayoclinic.org/symptoms/high-hemoglobin-count/basics/definition/sym-20050862"
    }, 
    "high potassium (hyperkalemia)": {
        "causes": [
            "acute kidney failure", 
            "chronic kidney disease", 
            "addison's disease (adrenal failure)", 
            "alcoholism or heavy drug use that causes rhabdomyolysis, a breakdown of muscle fibers that results in the release of potassium into the bloodstream", 
            "angiotensin-converting enzyme (ace) inhibitors", 
            "angiotensin ii receptor blockers (arbs)", 
            "destruction of red blood cells due to severe injury or burns", 
            "excessive use of potassium supplements", 
            "type 1 diabetes"
        ], 
        "url": "http://www.mayoclinic.org/symptoms/hyperkalemia/basics/definition/sym-20050776"
    }, 
    "high red blood cell count": {
        "causes": [
            "congenital heart disease in adults", 
            "heart failure", 
            "a condition present at birth that reduces the oxygen-carrying capacity of red blood cells (hemoglobinopathy)", 
            "high altitudes", 
            "copd (chronic obstructive pulmonary disease) and other lung diseases", 
            "sleep apnea", 
            "nicotine dependence (smoking)", 
            "anabolic steroids", 
            "blood doping (transfusion)", 
            "injections of a protein (erythropoietin) that enhances red blood cell production", 
            "dehydration (if the liquid component of the blood (plasma) is decreased, as in dehydration, the red blood cell count increases. this is due to the red blood cells becoming more concentrated. the actual number of red blood cells stays the same.)", 
            "polycythemia vera", 
            "other myeloproliferative disorders"
        ], 
        "url": "http://www.mayoclinic.org/symptoms/high-red-blood-cell-count/basics/definition/sym-20050858"
    }, 
    "high uric acid level": {
        "causes": [
            "diuretic medications (water pills)", 
            "drinking too much alcohol", 
            "genetics (inherited tendencies)", 
            "hypothyroidism (underactive thyroid)", 
            "immune-suppressing drugs", 
            "niacin, or vitamin b-3", 
            "obesity", 
            "psoriasis", 
            "purine-rich diet - liver, game meat, anchovies, sardines, gravy, dried beans and peas, mushrooms, and other foods", 
            "renal insufficiency - inability of the kidneys to filter waste", 
            "tumor lysis syndrome - a rapid release of cells into the blood caused by certain cancers or by chemotherapy for those cancers"
        ], 
        "url": "http://www.mayoclinic.org/symptoms/high-uric-acid-level/basics/definition/sym-20050607"
    }, 
    "high white blood cell count": {
        "causes": [
            "acute lymphocytic leukemia", 
            "acute myelogenous leukemia (aml)", 
            "allergy, especially severe allergic reactions", 
            "chronic lymphocytic leukemia", 
            "chronic myelogenous leukemia", 
            "drugs, such as corticosteroids and epinephrine", 
            "infections, bacterial or viral", 
            "myelofibrosis", 
            "polycythemia vera", 
            "rheumatoid arthritis", 
            "smoking", 
            "stress, such as severe emotional or physical stress", 
            "tuberculosis", 
            "whooping cough"
        ], 
        "url": "http://www.mayoclinic.org/symptoms/high-white-blood-cell-count/basics/definition/sym-20050611"
    }, 
    "hip pain": {
        "causes": [
            "juvenile rheumatoid arthritis", 
            "osteoarthritis", 
            "psoriatic arthritis", 
            "rheumatoid arthritis", 
            "septic arthritis", 
            "bursitis", 
            "dislocation", 
            "hip fracture", 
            "hip labral tear", 
            "inguinal hernia", 
            "tendinitis", 
            "meralgia paresthetica", 
            "sacroiliitis", 
            "sciatica", 
            "advanced (metastatic) cancer that has spread to the bones", 
            "bone cancer", 
            "leukemia", 
            "avascular necrosis", 
            "legg-calve-perthes disease (in children)", 
            "osteomyelitis", 
            "osteoporosis", 
            "synovitis"
        ], 
        "url": "http://www.mayoclinic.org/symptoms/hip-pain/basics/definition/sym-20050684"
    }, 
    "hypoxemia": {
        "causes": [
            "anemia", 
            "ards (acute respiratory distress syndrome)", 
            "asthma", 
            "congenital heart defects in children", 
            "congenital heart disease in adults", 
            "copd chronic obstructive pulmonary diseases", 
            "emphysema", 
            "interstitial lung disease", 
            "medications, such as certain narcotics and anesthetics, that depress breathing", 
            "strained or pulled abdominal muscle", 
            "pneumothorax (collapsed lung)", 
            "pulmonary edema", 
            "pulmonary embolism (blood clot in an artery in the lung)", 
            "sleep apnea"
        ], 
        "url": "http://www.mayoclinic.org/symptoms/hypoxemia/basics/definition/sym-20050930"
    }, 
    "intestinal gas": {
        "causes": [
            "beans and lentils", 
            "vegetables such as cabbage, broccoli, cauliflower, bok choy and brussels sprouts (cruciferous vegetables)", 
            "bran", 
            "dairy products containing lactose", 
            "fructose, which is found in some fruits and used as a sweetener in soft drinks and other products", 
            "sorbitol, a sugar substitute found in some sugar-free candies, gums and artificial sweeteners", 
            "carbonated beverages, such as soda or beer", 
            "autoimmune pancreatitis", 
            "celiac disease", 
            "crohn's disease", 
            "diabetes", 
            "dumping syndrome", 
            "eating disorders", 
            "gerd (gastroesophageal reflux disease)", 
            "gastroparesis", 
            "inflammatory bowel disease (ibd)", 
            "intestinal obstruction", 
            "duodenitis (inflammation of the initial portion of the small intestine)", 
            "lactose intolerance", 
            "peptic ulcer", 
            "ulcerative colitis"
        ], 
        "url": "http://www.mayoclinic.org/symptoms/intestinal-gas/basics/definition/sym-20050922"
    }, 
    "joint pain": {
        "causes": [
            "adult still's disease", 
            "ankylosing spondylitis", 
            "avascular necrosis", 
            "bone cancer", 
            "broken bone", 
            "bursitis", 
            "complex regional pain syndrome", 
            "dislocation", 
            "meralgia paresthetica", 
            "gonococcal arthritis", 
            "gout", 
            "hypothyroidism (underactive thyroid)", 
            "juvenile rheumatoid arthritis", 
            "leukemia", 
            "lupus", 
            "lyme disease", 
            "osteoarthritis", 
            "osteomyelitis", 
            "paget's disease of bone", 
            "polymyalgia rheumatica", 
            "pseudogout", 
            "psoriatic arthritis", 
            "reactive arthritis", 
            "rheumatoid arthritis", 
            "rickets", 
            "sarcoidosis", 
            "septic arthritis", 
            "sprains and strains", 
            "tendinitis"
        ], 
        "url": "http://www.mayoclinic.org/symptoms/joint-pain/basics/definition/sym-20050668"
    }, 
    "kidney pain": {
        "causes": [
            "bleeding in your kidney (hemorrhage)", 
            "blood clots in kidney veins (renal vein thrombosis)", 
            "salpingitis (inflammation of the fallopian tubes)", 
            "arteriosclerosis / atherosclerosis (hardening of the arteries leading to the kidneys)", 
            "horseshoe kidney, a condition present at birth in which the two kidneys are fused together", 
            "kidney cancer or kidney tumor", 
            "kidney infection (pyelonephritis)", 
            "kidney swelling due to a backup of urine (hydronephrosis)", 
            "polycystic kidney disease"
        ], 
        "url": "http://www.mayoclinic.org/symptoms/kidney-pain/basics/definition/sym-20050902"
    }, 
    "knee pain": {
        "causes": [
            "acl injury (anterior cruciate ligament injury)", 
            "avascular necrosis", 
            "baker's cyst", 
            "broken leg", 
            "collateral ligament injury", 
            "dislocation", 
            "gout", 
            "iliotibial band syndrome", 
            "knee bursitis", 
            "lupus", 
            "medial collateral ligament injury", 
            "osgood-schlatter disease", 
            "osteoarthritis", 
            "osteochondritis dissecans", 
            "osteomyelitis", 
            "patellar tendinitis", 
            "patellofemoral pain syndrome", 
            "posterior cruciate ligament injury", 
            "pseudogout", 
            "referred pain from hip area", 
            "septic arthritis", 
            "tendinitis", 
            "torn meniscus"
        ], 
        "url": "http://www.mayoclinic.org/symptoms/knee-pain/basics/definition/sym-20050688"
    }, 
    "leg pain": {
        "causes": [
            "achilles tendinitis", 
            "achilles tendon rupture", 
            "ankylosing spondylitis", 
            "acl injury (anterior cruciate ligament injury)", 
            "baker's cyst", 
            "bone cancer", 
            "broken leg", 
            "bursitis", 
            "chronic exertional compartment syndrome", 
            "claudication", 
            "deep vein thrombosis (dvt)", 
            "gout", 
            "growing pains", 
            "growth plate fractures", 
            "hamstring injury", 
            "herniated disk", 
            "infection", 
            "juvenile rheumatoid arthritis", 
            "knee bursitis", 
            "legg-calve-perthes disease", 
            "meralgia paresthetica", 
            "muscle cramp", 
            "muscle strain", 
            "night leg cramps", 
            "osgood-schlatter disease", 
            "osteoarthritis", 
            "osteochondritis dissecans", 
            "osteomyelitis", 
            "paget's disease of bone", 
            "patellar tendinitis", 
            "patellofemoral pain syndrome", 
            "peripheral artery disease", 
            "peripheral neuropathy", 
            "posterior cruciate ligament injury", 
            "pseudogout", 
            "psoriatic arthritis", 
            "reactive arthritis", 
            "rheumatoid arthritis", 
            "sacroiliitis", 
            "septic arthritis", 
            "sciatica", 
            "shin splints", 
            "spinal stenosis", 
            "stress fractures", 
            "tendinitis", 
            "thrombophlebitis", 
            "torn meniscus", 
            "varicose veins"
        ], 
        "url": "http://www.mayoclinic.org/symptoms/leg-pain/basics/definition/sym-20050784"
    }, 
    "leg swelling": {
        "causes": [
            "acute kidney failure", 
            "cardiomyopathy (disease of heart tissue)", 
            "chronic kidney disease", 
            "cirrhosis (scarring of the liver)", 
            "deep vein thrombosis (dvt)", 
            "heart failure", 
            "hormone therapy", 
            "lymphedema (blockage in the lymph system)", 
            "nephrotic syndrome (damage to small filtering blood vessels in the kidneys)", 
            "pain relievers, such as ibuprofen or naproxen", 
            "pericarditis (swelling of the membrane surrounding the heart)", 
            "pregnancy", 
            "prescription medications, including some used for diabetes and high blood pressure", 
            "sitting for a long time, such as during airline flights", 
            "standing for a long time", 
            "thrombophlebitis (a blood clot that usually occurs in the leg)", 
            "venous insufficiency, chronic (leg veins with a problem returning blood to the heart)", 
            "achilles tendon rupture", 
            "acl injury (tearing of the anterior cruciate ligament in your knee)", 
            "baker's cyst", 
            "broken ankle/broken foot", 
            "broken leg", 
            "cellulitis (a skin infection)", 
            "gout (arthritis related to excess uric acid)", 
            "infection or wound in the leg", 
            "knee bursitis (inflammation of fluid-filled sacs in the knee joint)", 
            "osteoarthritis (disease causing the breakdown of joints)", 
            "rheumatoid arthritis (inflammatory joint disease)", 
            "sprained ankle"
        ], 
        "url": "http://www.mayoclinic.org/symptoms/leg-swelling/basics/definition/sym-20050910"
    }, 
    "loss of smell": {
        "causes": [
            "acute sinusitis (sinus infection)", 
            "common cold", 
            "hay fever (allergic rhinitis)", 
            "influenza (flu)", 
            "nonallergic rhinitis (chronic congestion or sneezing not related to allergies)", 
            "bony deformity inside your nose", 
            "nasal polyps", 
            "tumors", 
            "aging", 
            "alzheimer's disease", 
            "brain aneurysm", 
            "brain surgery", 
            "brain tumor (both cancerous and noncancerous)", 
            "chemical exposures to certain insecticides or solvents", 
            "diabetes", 
            "huntington's disease", 
            "kallmann's syndrome (inability of testicles to produce sperm)", 
            "klinefelter syndrome (a condition in which males have an extra x chromosome in most of their cells)", 
            "korsakoff's psychosis (a brain disorder caused by the lack of thiamin)", 
            "malnutrition", 
            "medications (for example, some high blood pressure medications)", 
            "multiple sclerosis", 
            "multiple system atrophy (msa) (a progressive disorder of the nervous system)", 
            "paget's disease of bone (a disease that affects your bones, sometimes facial ones)", 
            "parkinson's disease", 
            "pick's disease (a form of dementia)", 
            "radiation therapy", 
            "rhinoplasty", 
            "schizophrenia", 
            "sjogren's syndrome (an inflammatory disease that generally causes dry mouth and eyes)", 
            "traumatic brain injury", 
            "zinc deficiency", 
            "zinc-containing nasal sprays (taken off the market in 2009)"
        ], 
        "url": "http://www.mayoclinic.org/symptoms/loss-of-smell/basics/definition/sym-20050804"
    }, 
    "low hemoglobin count": {
        "causes": [
            "your body produces fewer red blood cells than usual", 
            "your body destroys red blood cells faster than they can be produced", 
            "you experience blood loss", 
            "aplastic anemia", 
            "cancer", 
            "certain medications, such as anti-retroviral drugs for hiv infection and chemotherapy drugs for cancer and other conditions", 
            "cirrhosis", 
            "hodgkin's lymphoma (hodgkin's disease)", 
            "hypothyroidism (underactive thyroid)", 
            "iron deficiency anemia", 
            "chronic kidney disease", 
            "cystitis (bladder inflammation)", 
            "leukemia", 
            "multiple myeloma", 
            "myelodysplastic syndromes", 
            "gastritis (inflammation of the stomach lining)", 
            "vitamin deficiency anemia", 
            "enlarged spleen (splenomegaly) (splenomegaly)", 
            "porphyria", 
            "urinary tract infection (uti)", 
            "thalassemia", 
            "vasculitis", 
            "hemolysis", 
            "bleeding from a wound", 
            "bleeding in your digestive tract, such as from ulcers, cancers or hemorrhoids", 
            "bleeding in your urinary tract", 
            "frequent blood donation", 
            "heavy menstrual bleeding"
        ], 
        "url": "http://www.mayoclinic.org/symptoms/low-hemoglobin/basics/definition/sym-20050760"
    }, 
    "low potassium (hypokalemia)": {
        "causes": [
            "chronic kidney disease", 
            "diabetic ketoacidosis", 
            "diarrhea (causing anal irritation)", 
            "excessive alcohol use", 
            "excessive laxative use", 
            "excessive sweating", 
            "folic acid deficiency", 
            "prescription water or fluid pills (diuretics) use", 
            "primary aldosteronism", 
            "vomiting", 
            "some antibiotic use"
        ], 
        "url": "http://www.mayoclinic.org/symptoms/low-potassium/basics/definition/sym-20050632"
    }, 
    "low white blood cell count": {
        "causes": [
            "viral infections that temporarily disrupt the work of bone marrow", 
            "certain disorders present at birth (congenital) that involve diminished bone marrow function", 
            "cancer (or other diseases that damage bone marrow)", 
            "autoimmune disorders that destroy white blood cells or bone marrow cells", 
            "severe infections that use up white blood cells faster than they can be produced", 
            "medications, such as antibiotics, that destroy white blood cells", 
            "sarcoidosis", 
            "aplastic anemia", 
            "chemotherapy", 
            "radiation therapy", 
            "hiv/aids", 
            "hypersplenism - a premature destruction of blood cells by the spleen", 
            "tuberculosis (and other infectious diseases)", 
            "kostmann's syndrome - a congenital disorder involving low production of neutrophils", 
            "leukemia", 
            "lupus", 
            "rheumatoid arthritis and other autoimmune disorders", 
            "malnutrition and vitamin deficiencies", 
            "myelodysplastic syndromes", 
            "myelokathexis - a congenital disorder involving failure of neutrophils to enter the bloodstream"
        ], 
        "url": "http://www.mayoclinic.org/symptoms/low-white-blood-cell-count/basics/definition/sym-20050615"
    }, 
    "lymphocytosis": {
        "causes": [
            "infection (bacterial, viral, other)", 
            "cancer of the blood or lymphatic system", 
            "an autoimmune disorder causing ongoing (chronic) inflammation", 
            "acute lymphocytic leukemia", 
            "chronic lymphocytic leukemia", 
            "cytomegalovirus (cmv) infection", 
            "hiv/aids", 
            "mononucleosis", 
            "other viral infections", 
            "tuberculosis", 
            "vasculitis", 
            "whooping cough"
        ], 
        "url": "http://www.mayoclinic.org/symptoms/lymphocytosis/basics/definition/sym-20050660"
    }, 
    "muscle pain": {
        "causes": [
            "chronic exertional compartment syndrome", 
            "chronic fatigue syndrome", 
            "claudication", 
            "dermatomyositis", 
            "dystonia", 
            "fibromyalgia", 
            "hypothyroidism (underactive thyroid)", 
            "influenza (flu)", 
            "lupus", 
            "lyme disease", 
            "medications, especially the cholesterol medications known as statins", 
            "muscle cramp", 
            "myofascial pain syndrome", 
            "polymyalgia rheumatica", 
            "polymyositis", 
            "repetitive strain injuries", 
            "rheumatoid arthritis", 
            "rocky mountain spotted fever"
        ], 
        "url": "http://www.mayoclinic.org/symptoms/muscle-pain/basics/definition/sym-20050866"
    }, 
    "nasal congestion": {
        "causes": [
            "acute sinusitis", 
            "allergies", 
            "chronic sinusitis", 
            "churg-strauss syndrome", 
            "common cold", 
            "decongestant nasal spray overuse", 
            "deviated septum", 
            "drug addiction", 
            "dry air", 
            "enlarged adenoids", 
            "foreign body in the nose", 
            "hormonal changes", 
            "influenza (flu)", 
            "medications, such as high blood pressure drugs", 
            "nasal polyps", 
            "nonallergic rhinitis", 
            "occupational asthma", 
            "pregnancy", 
            "respiratory syncytial virus (rsv)", 
            "stress", 
            "thyroid disorders", 
            "tobacco smoke", 
            "granulomatosis with polyangiitis (wegener's granulomatosis)"
        ], 
        "url": "http://www.mayoclinic.org/symptoms/nasal-congestion/basics/definition/sym-20050644"
    }, 
    "nausea and vomiting": {
        "causes": [
            "chemotherapy", 
            "gastroparesis (a condition in which the muscles of the stomach wall don't function properly, interfering with digestion)", 
            "general anesthesia", 
            "intestinal obstruction", 
            "motion sickness: first aid", 
            "morning sickness", 
            "migraine", 
            "rotavirus", 
            "viral gastroenteritis (stomach flu)", 
            "vestibular neuritis", 
            "alcohol use disorder", 
            "(in children)", 
            "anorexia nervosa", 
            "appendicitis", 
            "benign paroxysmal positional vertigo (bppv)", 
            "brain tumor (both cancerous and noncancerous)", 
            "bulimia nervosa", 
            "concussion", 
            "cholecystitis", 
            "cholecystitis (gallbladder inflammation)", 
            "cyclic vomiting syndrome", 
            "depression (major depressive disorder)", 
            "dizziness", 
            "diabetic ketoacidosis", 
            "ear infection (middle ear)", 
            "food poisoning", 
            "generalized anxiety disorder", 
            "gerd (gastroesophageal reflux disease)", 
            "hiatal hernia", 
            "heart failure", 
            "gallstones", 
            "fever (in children)", 
            "hydrocephalus (a congenital brain abnormality)", 
            "hyperparathyroidism (overactive parathyroid)", 
            "hyperthyroidism (overactive thyroid)", 
            "hypoparathyroidism (underactive parathyroid)", 
            "intestinal ischemia", 
            "enlarged spleen (splenomegaly)", 
            "intracranial hematoma", 
            "intussusception (in children)", 
            "duodenitis (inflammation of the initial portion of the small intestine)", 
            "liver cancer", 
            "liver failure", 
            "medications (including aspirin, nonsteroidal anti-inflammatories, oral contraceptives, digitalis, narcotics and antibiotics)", 
            "meniere's disease", 
            "meningitis", 
            "milk allergy (in infants and children)", 
            "pancreatic cancer", 
            "pancreatitis", 
            "peptic ulcer", 
            "pseudotumor cerebri", 
            "pyloric stenosis (in infants)", 
            "radiation therapy", 
            "severe pain", 
            "traumatic brain injury"
        ], 
        "url": "http://www.mayoclinic.org/symptoms/nausea/basics/definition/sym-20050736"
    }, 
    "neck pain": {
        "causes": [
            "carrying a heavy backpack or purse on one shoulder", 
            "cervical dystonia (spasmodic torticollis)", 
            "cervical spondylosis", 
            "cradling your phone between your shoulder and neck", 
            "emotional stress", 
            "meralgia paresthetica", 
            "herniated disk", 
            "meningitis", 
            "ankylosing spondylitis", 
            "osteoarthritis", 
            "poor posture", 
            "rheumatoid arthritis", 
            "sleeping on your abdomen or with too many or too few pillows", 
            "spinal stenosis", 
            "tension headache", 
            "tmj disorders", 
            "trauma from accidents or falls", 
            "whiplash"
        ], 
        "url": "http://www.mayoclinic.org/symptoms/neck-pain/basics/definition/sym-20050882"
    }, 
    "neutropenia": {
        "causes": [
            "kostmann's syndrome - a congenital disorder involving low production of neutrophils", 
            "myelokathexis - a congenital disorder involving failure of neutrophils to enter the bloodstream", 
            "leukemia", 
            "myelodysplastic syndromes", 
            "myelofibrosis", 
            "chemotherapy", 
            "alcohol use disorder", 
            "chronic idiopathic neutropenia in adults", 
            "vitamin deficiencies", 
            "hepatitis a", 
            "hepatitis b", 
            "hepatitis c", 
            "hiv/aids", 
            "lyme disease", 
            "malaria", 
            "salmonella infection", 
            "sepsis - an overwhelming bloodstream infection that uses up neutrophils faster than they can be produced", 
            "other viral infections that disrupt the work of bone marrow", 
            "rheumatoid arthritis and other autoimmune disorders", 
            "medications, such as antibiotics", 
            "hypersplenism - an abnormality of the spleen causing blood cell destruction"
        ], 
        "url": "http://www.mayoclinic.org/symptoms/neutropenia/basics/definition/sym-20050854"
    }, 
    "night leg cramps": {
        "causes": [
            "peripheral artery disease", 
            "spinal stenosis", 
            "acute kidney failure", 
            "addison's disease", 
            "anemia", 
            "chronic kidney disease", 
            "cirrhosis", 
            "hyperthyroidism", 
            "hypothyroidism (underactive thyroid)", 
            "type 1 diabetes", 
            "type 2 diabetes", 
            "blood pressure drugs", 
            "diuretics (water retention relievers)", 
            "oral contraceptives", 
            "cholesterol-lowering drugs (statins)", 
            "dialysis", 
            "dehydration", 
            "diarrhea (causing anal irritation)", 
            "muscle fatigue", 
            "nerve damage, as from cancer treatments", 
            "osteoarthritis", 
            "parkinson's disease", 
            "pregnancy"
        ], 
        "url": "http://www.mayoclinic.org/symptoms/night-leg-cramps/basics/definition/sym-20050813"
    }, 
    "night sweats": {
        "causes": [
            "depression medications (antidepressants)", 
            "drugs used to regulate your hormones (hormone therapy)", 
            "drugs that lower the level of sugar in your blood (hypoglycemic agents)", 
            "anxiety", 
            "autonomic neuropathy (damage to your autonomic nerves)", 
            "brucellosis (a bacterial infection)", 
            "carcinoid syndrome (a syndrome resulting from a certain type of cancerous tumor)", 
            "endocarditis (an infection of your heart lining)", 
            "hiv/aids", 
            "hodgkin's lymphoma (hodgkin's disease)", 
            "hyperthyroidism (overactive thyroid)", 
            "leukemia", 
            "menopause", 
            "myelofibrosis (a bone marrow disorder)", 
            "gastritis (inflammation of the stomach lining)", 
            "osteomyelitis (a bone infection)", 
            "pheochromocytoma (a rare adrenal gland tumor)", 
            "pyogenic abscess (a pus-filled cavity caused by an infection)", 
            "sleep disorders (such as obstructive sleep apnea)", 
            "stroke", 
            "syringomyelia (a fluid-filled cyst in the spinal cord)", 
            "tuberculosis"
        ], 
        "url": "http://www.mayoclinic.org/symptoms/night-sweats/basics/definition/sym-20050768"
    }, 
    "nipple discharge": {
        "causes": [
            "you have a lump in your breast", 
            "only one breast is affected", 
            "the discharge contains blood", 
            "the discharge is spontaneous and persistent", 
            "the discharge affects only a single duct", 
            "abscess", 
            "birth control pills", 
            "breast cancer", 
            "breast infection", 
            "ductal carcinoma in situ (dcis)", 
            "endocrine disorders", 
            "excessive breast stimulation", 
            "fibrocystic breasts", 
            "galactorrhea", 
            "injury or trauma to the breast", 
            "intraductal papilloma", 
            "mammary duct ectasia", 
            "medication use", 
            "menstrual cycle hormone changes", 
            "paget's disease of the breast", 
            "periductal mastitis", 
            "pregnancy and breast-feeding", 
            "prolactinoma"
        ], 
        "url": "http://www.mayoclinic.org/symptoms/nipple-discharge/basics/definition/sym-20050946"
    }, 
    "nosebleeds": {
        "causes": [
            "dry air - when your nasal membranes dry out, they're more susceptible to bleeding and infections", 
            "nose picking", 
            "acute sinusitis", 
            "allergies", 
            "aspirin use", 
            "hemophilia (and other bleeding disorders)", 
            "blood thinners (anticoagulants), such as warfarin and heparin", 
            "chemical irritants, such as ammonia", 
            "chronic sinusitis", 
            "cocaine use", 
            "common cold", 
            "deviated septum", 
            "foreign body in the nose", 
            "nasal sprays, such as those used to treat allergies, if used frequently", 
            "nonallergic rhinitis", 
            "trauma to the nose", 
            "alcohol use", 
            "hereditary hemorrhagic telangiectasia", 
            "idiopathic thrombocytopenic purpura (itp)", 
            "leukemia", 
            "nasal polyps", 
            "nasal surgery", 
            "nasal tumor", 
            "second trimester pregnancy"
        ], 
        "url": "http://www.mayoclinic.org/symptoms/nosebleeds/basics/definition/sym-20050914"
    }, 
    "numbness": {
        "causes": [
            "acoustic neuroma", 
            "alcohol use disorder", 
            "amyloidosis", 
            "brachial plexus injury", 
            "brain aneurysm", 
            "brain avm (arteriovenous malformation)", 
            "brain tumor", 
            "carpal tunnel syndrome", 
            "charcot-marie-tooth disease", 
            "diabetes", 
            "fabry's disease", 
            "guillain-barre syndrome", 
            "heavy metal exposure", 
            "herniated disk", 
            "leprosy", 
            "lyme disease", 
            "multiple sclerosis", 
            "paraneoplastic syndromes of the nervous system", 
            "peripheral nerve compression (ulnar or peroneal nerves)", 
            "peripheral neuropathy", 
            "porphyria", 
            "raynaud's disease", 
            "shingles", 
            "side effects of chemotherapy or anti-hiv drugs", 
            "sjogren's syndrome", 
            "spinal cord injury", 
            "spinal cord tumor", 
            "stroke", 
            "syphilis", 
            "kidney cancer", 
            "transient ischemic attack (tia)", 
            "vasculitis (blood vessel inflammation)", 
            "vitamin b-12 deficiency"
        ], 
        "url": "http://www.mayoclinic.org/symptoms/numbness/basics/definition/sym-20050938"
    }, 
    "numbness in hands": {
        "causes": [
            "alcohol use disorder", 
            "amyloidosis", 
            "brachial plexus injury", 
            "carpal tunnel syndrome (cubital tunnel syndrome)", 
            "cervical spondylosis", 
            "ganglion cyst", 
            "guillain-barre syndrome", 
            "hiv/aids", 
            "lyme disease", 
            "multiple sclerosis", 
            "paraneoplastic syndromes of the nervous system", 
            "peripheral neuropathy", 
            "raynaud's disease", 
            "side effects of chemotherapy drugs", 
            "sjogren's syndrome", 
            "spinal cord injury", 
            "stroke", 
            "syphilis", 
            "type 2 diabetes", 
            "ulnar nerve compression", 
            "vasculitis", 
            "vitamin b-12 deficiency"
        ], 
        "url": "http://www.mayoclinic.org/symptoms/numbness-in-hands/basics/definition/sym-20050842"
    }, 
    "painful urination (dysuria)": {
        "causes": [
            "bladder stones", 
            "chlamydia", 
            "cystitis (bladder infection)", 
            "drugs, such as those used in cancer treatment, that have bladder irritation as a side effect", 
            "genital herpes", 
            "forgotten (retained) tampon", 
            "having a recent urinary tract procedure performed, including use of urologic instruments for testing or treatment", 
            "kidney infection", 
            "kidney stones", 
            "prostatitis (infection or inflammation of the prostate)", 
            "sexually transmitted infections (stis)", 
            "soaps, perfumes and other personal care products", 
            "urethral stricture (narrowing of the urethra)", 
            "urethritis (infection of the urethra)", 
            "salpingitis (inflammation of the fallopian tubes)", 
            "vaginitis (vaginal infection)", 
            "yeast infection (vaginal)"
        ], 
        "url": "http://www.mayoclinic.org/symptoms/painful-urination/basics/definition/sym-20050772"
    }, 
    "peeling skin": {
        "causes": [
            "allergies", 
            "infections, including some types of staph and fungal infections", 
            "immune system disorders", 
            "cancer and cancer treatment", 
            "genetic disease, including a rare skin disorder called acral peeling skin syndrome that causes painless peeling of the top layer of skin", 
            "athlete's foot", 
            "atopic dermatitis (eczema)", 
            "contact dermatitis", 
            "cutaneous t-cell lymphoma", 
            "dry skin", 
            "hyperhidrosis", 
            "jock itch", 
            "medication side effects", 
            "non-hodgkin's lymphoma", 
            "pemphigus", 
            "psoriasis", 
            "ringworm (body)", 
            "ringworm (scalp)", 
            "scarlet fever", 
            "seborrheic dermatitis", 
            "staph infections", 
            "stevens-johnson syndrome", 
            "sunburn: soothing solutions", 
            "toxic shock syndrome"
        ], 
        "url": "http://www.mayoclinic.org/symptoms/peeling-skin/basics/definition/sym-20050672"
    }, 
    "pelvic pain": {
        "causes": [
            "adenomyosis", 
            "endometriosis", 
            "menstrual cramps (dysmenorrhea)", 
            "ectopic pregnancy (or other pregnancy-related conditions)", 
            "(before the 20th week) or intrauterine fetal death", 
            "mittelschmerz (ovulation pain)", 
            "ovarian cancer", 
            "ovarian cysts", 
            "pelvic inflammatory disease (pid)", 
            "uterine fibroids", 
            "vulvodynia", 
            "appendicitis", 
            "colon cancer", 
            "chronic constipation", 
            "cholecystitis (gallbladder inflammation)", 
            "diverticulitis", 
            "fibromyalgia", 
            "inguinal hernia", 
            "interstitial cystitis (also called painful bladder syndrome)", 
            "enlarged spleen (splenomegaly)", 
            "duodenitis (inflammation of the initial portion of the small intestine)", 
            "kidney stones", 
            "past physical or sexual abuse", 
            "pelvic floor muscle spasms", 
            "prostatitis", 
            "ulcerative colitis", 
            "salpingitis (inflammation of the fallopian tubes)"
        ], 
        "url": "http://www.mayoclinic.org/symptoms/pelvic-pain/basics/definition/sym-20050898"
    }, 
    "petechiae": {
        "causes": [
            "crying", 
            "coughing", 
            "vomiting", 
            "childbirth", 
            "weightlifting", 
            "anticoagulants (warfarin, heparin)", 
            "atropine (atropen)", 
            "carbamazepine (carbatrol, epitol, tegretol, others)", 
            "chloral hydrate (somnote)", 
            "desipramine (norpramin)", 
            "indomethacin (indocin)", 
            "naproxen (aleve, anaprox, naprosyn)", 
            "nitrofurantoin (furadantin, macrobid, macrodantin)", 
            "penicillin", 
            "quinine (qualaquin)", 
            "cytomegalovirus (cmv) infection", 
            "endocarditis", 
            "hantavirus pulmonary syndrome", 
            "meningococcemia", 
            "mononucleosis", 
            "rocky mountain spotted fever", 
            "scarlet fever", 
            "sepsis - an overwhelming bloodstream infection that uses up neutrophils faster than they can be produced", 
            "strep throat", 
            "viral hemorrhagic fevers", 
            "vasculitis", 
            "thrombocytopenia (low platelet count)", 
            "leukemia", 
            "scurvy (vitamin c deficiency)", 
            "vitamin k deficiency"
        ], 
        "url": "http://www.mayoclinic.org/symptoms/petechiae/basics/definition/sym-20050724"
    }, 
    "protein in urine": {
        "causes": [
            "cold exposure", 
            "emotional stress", 
            "fever", 
            "heat exposure", 
            "strenuous exercise", 
            "amyloidosis (buildup of abnormal proteins in your organs)", 
            "certain drugs", 
            "chronic kidney disease", 
            "diabetes", 
            "glomerulonephritis (inflammation in the kidney cells that filter waste from the blood)", 
            "goodpasture's syndrome (disease involving the kidneys and lungs)", 
            "heart disease", 
            "heart failure", 
            "high blood pressure (hypertension)", 
            "hodgkin's lymphoma (hodgkin's disease)", 
            "iga nephropathy (berger's disease) (kidney inflammation resulting from a buildup of the antibody immunoglobulin a)", 
            "kidney infection", 
            "leukemia", 
            "lupus", 
            "malaria", 
            "multiple myeloma", 
            "orthostatic proteinuria (urine protein level rises when in an upright position)", 
            "pericarditis (inflammation of the sac that surrounds the heart)", 
            "preeclampsia", 
            "pregnancy", 
            "rheumatoid arthritis", 
            "sarcoidosis (development and growth of clumps of inflammatory cells in your organs)", 
            "urinary tract infection (uti)"
        ], 
        "url": "http://www.mayoclinic.org/symptoms/protein-in-urine/basics/definition/sym-20050656"
    }, 
    "rectal bleeding": {
        "causes": [
            "anal fissure (tear in the skin of the anus)", 
            "chronic constipation", 
            "hard stools", 
            "hemorrhoids", 
            "anal cancer", 
            "angiodysplasia (abnormalities in the blood vessels near the intestines)", 
            "colon cancer", 
            "colon polyps", 
            "cholecystitis (gallbladder inflammation)", 
            "diarrhea (causing anal irritation)", 
            "diverticulosis (a bulging pouch that forms on the wall of the intestine)", 
            "ischemic colitis (colon inflammation caused by reduced blood flow)", 
            "ganglion cyst (colon inflammation caused by an infection)", 
            "radiation therapy", 
            "rectal prolapse (part of the rectum protrudes through the anus)", 
            "solitary rectal ulcer syndrome (a sore on the wall of the rectum)", 
            "ulcerative colitis"
        ], 
        "url": "http://www.mayoclinic.org/symptoms/rectal-bleeding/basics/definition/sym-20050740"
    }, 
    "red eye": {
        "causes": [
            "allergies", 
            "blepharitis (inflammation that affects your eyelids)", 
            "chalazion", 
            "corneal abrasion (scratch): first aid", 
            "corneal herpetic infections (herpes)", 
            "corneal ulcer", 
            "dry eyes (decreased production of tears)", 
            "ectropion (outwardly turned eyelid)", 
            "entropion (inwardly turned eyelid)", 
            "episcleritis (inflammation of the membrane covering the white part of the eye)", 
            "eyedrops", 
            "foreign object in the eye: first aid", 
            "glaucoma (group of conditions that damage the optic nerve)", 
            "hay fever", 
            "injury, such as from a blunt trauma or burn", 
            "iritis (inflammation of the colored part of the eye)", 
            "keratitis (inflammation of the cornea)", 
            "orbital cellulitis (severe infection of tissues around the eye)", 
            "pink eye (conjunctivitis)", 
            "scleritis (inflammation of the white part of the eye)", 
            "sty (a red, painful lump near the edge of your eyelid)", 
            "subconjunctival hemorrhage (broken blood vessel in eye) (broken blood vessel in eye)", 
            "uveitis (inflammation of the middle layer of the eye)"
        ], 
        "url": "http://www.mayoclinic.org/symptoms/red-eye/basics/definition/sym-20050748"
    }, 
    "runny nose": {
        "causes": [
            "acute sinusitis", 
            "allergies", 
            "chronic sinusitis", 
            "churg-strauss syndrome", 
            "common cold", 
            "decongestant nasal spray overuse", 
            "deviated septum", 
            "drug addiction", 
            "dry air", 
            "granulomatosis with polyangiitis (wegener's granulomatosis)", 
            "hormonal changes", 
            "influenza (flu)", 
            "lodged object", 
            "medications", 
            "nasal polyps", 
            "nonallergic rhinitis", 
            "occupational asthma", 
            "pregnancy", 
            "respiratory syncytial virus (rsv)", 
            "spinal fluid leak", 
            "tobacco smoke"
        ], 
        "url": "http://www.mayoclinic.org/symptoms/runny-nose/basics/definition/sym-20050640"
    }, 
    "shortness of breath": {
        "causes": [
            "asthma (bronchospasm)", 
            "carbon monoxide poisoning", 
            "cardiac tamponade (excess fluid around the heart)", 
            "hiatal hernia", 
            "heart failure", 
            "low blood pressure (hypotension)", 
            "pulmonary embolism (blood clot in an artery in the lung)", 
            "pneumothorax (collapsed lung)", 
            "pneumonia (pulmonary infection)", 
            "sudden blood loss", 
            "upper airway obstruction (blockage in the breathing passage)", 
            "asthma", 
            "copd (chronic obstructive pulmonary disease)", 
            "deconditioning", 
            "heart dysfunction", 
            "interstitial lung disease", 
            "obesity", 
            "croup (in young children)", 
            "lung cancer", 
            "pleurisy (inflammation of the membrane lining the chest)", 
            "pulmonary edema (excess fluid in the lungs)", 
            "(scarred and damaged lungs)", 
            "pulmonary hypertension (high blood pressure within the lungs' blood vessels)", 
            "sarcoidosis (collections of inflammatory cells in the body)", 
            "tuberculosis", 
            "cardiomyopathy (problem with the heart muscle)", 
            "heart arrhythmias (rhythm problems)", 
            "pericarditis (swelling of the membrane surrounding the heart)", 
            "anemia", 
            "broken ribs", 
            "choking: first aid", 
            "epiglottitis (swelling of part of the windpipe)", 
            "foreign object inhaled: first aid", 
            "generalized anxiety disorder", 
            "guillain-barre syndrome", 
            "myasthenia gravis (condition causing muscle weakness)"
        ], 
        "url": "http://www.mayoclinic.org/symptoms/shortness-of-breath/basics/definition/sym-20050890"
    }, 
    "shoulder pain": {
        "causes": [
            "avascular necrosis", 
            "brachial plexus injury", 
            "broken arm", 
            "broken collarbone", 
            "bursitis", 
            "cervical radiculopathy", 
            "dislocated shoulder", 
            "frozen shoulder", 
            "hiatal hernia", 
            "impingement", 
            "osteoarthritis", 
            "polymyalgia rheumatica", 
            "rheumatoid arthritis", 
            "rotator cuff injury", 
            "separated shoulder", 
            "septic arthritis", 
            "sprains and strains", 
            "tendinitis", 
            "tendon rupture", 
            "thoracic outlet syndrome", 
            "torn cartilage"
        ], 
        "url": "http://www.mayoclinic.org/symptoms/shoulder-pain/basics/definition/sym-20050696"
    }, 
    "testicle pain": {
        "causes": [
            "diabetic neuropathy (nerve damage caused by diabetes)", 
            "drug side effect, such as certain antibiotics and chemotherapy drugs", 
            "epididymitis (testicle inflammation)", 
            "gangrene (specifically, a type of gangrene called fournier's gangrene)", 
            "overview (blood vessel inflammation)", 
            "hydrocele (fluid buildup that causes swelling of the scrotum)", 
            "idiopathic testicular pain (unknown cause)", 
            "inguinal hernia", 
            "kidney stones", 
            "mumps", 
            "orchitis (inflamed testicle)", 
            "prostatitis (infection or inflammation of the prostate)", 
            "scrotal masses", 
            "spermatocele (fluid buildup in the testicle)", 
            "testicle injury or blow to the testicles", 
            "testicular cancer", 
            "testicular torsion (twisted testicle)", 
            "undescended testicle (also called cryptorchidism)", 
            "urinary tract infection (uti)", 
            "varicocele (enlarged veins in the scrotum)", 
            "vasectomy"
        ], 
        "url": "http://www.mayoclinic.org/symptoms/testicle-pain/basics/definition/sym-20050942"
    }, 
    "unexplained weight loss": {
        "causes": [
            "addison's disease (adrenal insufficiency)", 
            "cancer", 
            "celiac disease", 
            "changes in diet or appetite", 
            "changes in sense of smell", 
            "changes in sense of taste", 
            "copd (chronic obstructive pulmonary disease) and other lung diseases", 
            "cholecystitis (gallbladder inflammation)", 
            "dementia", 
            "dental problems", 
            "depression (major depressive disorder)", 
            "diabetes", 
            "heart failure", 
            "hiv/aids", 
            "hypercalcemia", 
            "hyperthyroidism (overactive thyroid)", 
            "hypothyroidism (underactive thyroid)", 
            "medications", 
            "parkinson's disease", 
            "peptic ulcer", 
            "substance abuse (alcohol, cocaine, other)", 
            "tuberculosis", 
            "ulcerative colitis"
        ], 
        "url": "http://www.mayoclinic.org/symptoms/unexplained-weight-loss/basics/definition/sym-20050700"
    }, 
    "urine odor": {
        "causes": [
            "bladder infection", 
            "cystitis (bladder inflammation)", 
            "dehydration", 
            "diabetic ketoacidosis (high levels of blood acids called ketones)", 
            "gastrointestinal-bladder fistula (abnormal connection between the intestines and bladder)", 
            "maple syrup urine disease (rare genetic disease that causes difficulty breaking down certain amino acids)", 
            "metabolic disorder (a problem with the way your body converts the foods you eat into energy)", 
            "type 2 diabetes (uncontrolled)", 
            "salpingitis (inflammation of the fallopian tubes)"
        ], 
        "url": "http://www.mayoclinic.org/symptoms/urine-odor/basics/definition/sym-20050704"
    }, 
    "vaginal bleeding": {
        "causes": [
            "cervical cancer", 
            "endometrial cancer (uterine cancer)", 
            "endometrial hyperplasia", 
            "ovarian cancer", 
            "uterine sarcoma", 
            "vaginal cancer", 
            "hyperthyroidism", 
            "hypothyroidism", 
            "polycystic ovary syndrome (pcos)", 
            "ectopic pregnancy", 
            "fluctuating hormone levels", 
            "(before the 20th week of pregnancy)", 
            "pregnancy", 
            "random ovulatory cycles", 
            "sexual intercourse", 
            "perimenopause", 
            "vaginal atrophy (genitourinary syndrome of menopause)", 
            "cervicitis", 
            "chlamydia", 
            "endometritis", 
            "gonorrhea", 
            "pelvic inflammatory disease (pid)", 
            "ureaplasma vaginitis", 
            "vaginitis", 
            "celiac disease", 
            "severe systemic disease, such as kidney or liver disease", 
            "thrombocytopenia", 
            "von willebrand disease (and other blood clotting disorders)", 
            "forgotten (retained) tampon", 
            "intrauterine device (iud)", 
            "stopping or changing birth control pills or menopausal hormone therapy (withdrawal bleeding)", 
            "tamoxifen side effect", 
            "adenomyosis", 
            "cervical polyps", 
            "endometrial polyps", 
            "uterine fibroids", 
            "uterine polyps", 
            "blunt trauma or penetrating injury to the vagina or cervix", 
            "sexual abuse"
        ], 
        "url": "http://www.mayoclinic.org/symptoms/vaginal-bleeding/basics/definition/sym-20050756"
    }, 
    "vaginal bleeding after sex": {
        "causes": [
            "cervicitis", 
            "cervical ectropion, a condition in which the inner lining of the cervix protrudes through the cervical opening and grows on the vaginal part of the cervix", 
            "cervical polyps, noncancerous (benign) growths on your cervix", 
            "cervicitis (inflammation of the cervix)", 
            "friction during sexual intercourse", 
            "genital sores that result from sexually transmitted infections, such as genital herpes or syphilis", 
            "inadequate lubrication or foreplay", 
            "injury to the uterine lining (endometrium) during intercourse, especially in women taking oral contraceptives", 
            "normal uterine bleeding, if you're just beginning your period or if it has just ended", 
            "trauma from sexual abuse", 
            "vaginal atrophy", 
            "vaginal dryness", 
            "vaginitis"
        ], 
        "url": "http://www.mayoclinic.org/symptoms/bleeding-after-vaginal-sex/basics/definition/sym-20050716"
    }, 
    "vaginal discharge": {
        "causes": [
            "bacterial vaginosis", 
            "cervicitis", 
            "chlamydia", 
            "gonorrhea", 
            "forgotten (retained) tampon", 
            "pelvic inflammatory disease (pid)", 
            "sexually transmitted diseases", 
            "trichomoniasis", 
            "vaginitis", 
            "yeast infection (vaginal)", 
            "certain hygiene practices, such as douching or using scented sprays or soaps", 
            "cervical cancer", 
            "pregnancy", 
            "rectovaginal fistula", 
            "vaginal atrophy (genitourinary syndrome of menopause)", 
            "vaginal cancer", 
            "vaginal fistula"
        ], 
        "url": "http://www.mayoclinic.org/symptoms/vaginal-discharge/basics/definition/sym-20050825"
    }, 
    "vaginal dryness": {
        "causes": [
            "breast-feeding", 
            "childbirth", 
            "nicotine dependence", 
            "cancer treatment (effects on your ovaries from cancer therapy)", 
            "primary immunodeficiency", 
            "menopause", 
            "perimenopause (the transition time before menopause)", 
            "oophorectomy (ovary removal surgery)", 
            "use of allergy and cold medications or anti-estrogen medications", 
            "douching", 
            "sjogren's syndrome"
        ], 
        "url": "http://www.mayoclinic.org/symptoms/vaginal-dryness/basics/definition/sym-20151520"
    }, 
    "vaginal odor": {
        "causes": [
            "bacterial vaginosis", 
            "poor hygiene", 
            "retained or forgotten tampon", 
            "trichomoniasis", 
            "rectovaginal fistula (an abnormal opening between the rectum and vagina that allows feces to leak into the vagina)", 
            "cervical cancer", 
            "vaginal cancer"
        ], 
        "url": "http://www.mayoclinic.org/symptoms/vaginal-odor/basics/definition/sym-20050664"
    }, 
    "vomiting blood": {
        "causes": [
            "acute liver failure", 
            "alcohol use disorder", 
            "aspirin", 
            "benign tumors of the stomach or esophagus", 
            "cirrhosis (scarring of the liver)", 
            "defects in gastrointestinal tract blood vessels", 
            "dieulafoy's lesion (an artery that protrudes through the stomach wall)", 
            "duodenitis (inflammation in the first part of the small intestine)", 
            "esophageal cancer", 
            "esophageal varices (enlarged veins in the esophagus)", 
            "esophagitis (inflammation of the esophagus)", 
            "gastric erosions (breakdown of tissue lining the stomach)", 
            "gastric varices (enlarged veins in the stomach)", 
            "gastritis (inflammation of the stomach)", 
            "mallory-weiss tear (tear in the esophagus associated with pressure caused by vomiting or coughing)", 
            "nonsteroidal anti-inflammatory drugs", 
            "pancreatic cancer", 
            "pancreatitis (pancreas inflammation)", 
            "peptic ulcer", 
            "portal hypertension (high blood pressure in the portal vein)", 
            "prolonged or vigorous vomiting", 
            "stomach cancer", 
            "birth defects", 
            "blood clotting disorders", 
            "milk allergy", 
            "swallowed blood, such as from the nose", 
            "swallowed object", 
            "vitamin k deficiency"
        ], 
        "url": "http://www.mayoclinic.org/symptoms/vomiting-blood/basics/definition/sym-20050732"
    }, 
    "watery eyes": {
        "causes": [
            "chemotherapy drugs", 
            "epinephrine", 
            "eyedrops, especially echothiophate iodide and pilocarpine", 
            "allergies", 
            "blepharitis (eyelid inflammation)", 
            "blocked tear duct", 
            "common cold", 
            "corneal abrasion (scratch): first aid", 
            "corneal ulcer", 
            "dry eyes (decreased production of tears)", 
            "ectropion (outwardly turned eyelid)", 
            "entropion (inwardly turned eyelid)", 
            "foreign object in the eye: first aid", 
            "hay fever", 
            "ingrown eyelash (trichiasis)", 
            "keratitis", 
            "pink eye (conjunctivitis)", 
            "sty", 
            "tear duct infection", 
            "trachoma", 
            "bell's palsy", 
            "blow to the eye or other eye injury", 
            "burns", 
            "chemical splash in the eye: first aid", 
            "chronic sinusitis", 
            "facial nerve palsy", 
            "inflammatory diseases", 
            "radiation therapy", 
            "rheumatoid arthritis", 
            "sarcoidosis", 
            "sjogren's syndrome", 
            "stevens-johnson syndrome", 
            "surgery of the eye or nose", 
            "thyroid disorders", 
            "tumors affecting the tear drainage system", 
            "granulomatosis with polyangiitis (wegener's granulomatosis)"
        ], 
        "url": "http://www.mayoclinic.org/symptoms/watery-eyes/basics/definition/sym-20050821"
    }, 
    "wheezing": {
        "causes": [
            "allergies", 
            "(a severe allergic reaction, such as to an insect bite or medication)", 
            "asthma", 
            "bronchiectasis, a chronic lung condition in which abnormal widening of bronchial tubes inhibits mucus clearing", 
            "bronchiolitis (especially in young children)", 
            "bronchitis", 
            "childhood asthma", 
            "copd (chronic obstructive pulmonary disease) and other lung diseases", 
            "emphysema", 
            "epiglottitis (swelling of the \"lid\" of your windpipe)", 
            "foreign object inhaled: first aid", 
            "gerd (gastroesophageal reflux disease)", 
            "heart failure", 
            "lung cancer", 
            "medications (particularly aspirin)", 
            "strained or pulled abdominal muscle", 
            "respiratory syncytial virus (rsv) (especially in young children)", 
            "respiratory tract infection (especially in children younger than 2)", 
            "sleep apnea, obstructive (a condition in which breathing stops and starts during sleep)", 
            "smoking", 
            "vocal cord dysfunction (a condition that affects vocal cord movement)"
        ], 
        "url": "http://www.mayoclinic.org/symptoms/wheezing/basics/definition/sym-20050764"
    }, 
    "white tongue": {
        "causes": [
            "poor oral hygiene", 
            "dry mouth", 
            "congenital heart disease in adults", 
            "smoking or other oral tobacco use", 
            "alcohol use", 
            "mouth breathing", 
            "low roughage diet - eating mostly soft or mashed foods", 
            "mechanical irritation from sharp tooth edges or dental appliances", 
            "fever", 
            "use of certain medications, such as prolonged use of antibiotics that may bring on an oral yeast infection", 
            "oral thrush", 
            "geographic tongue", 
            "leukoplakia", 
            "oral lichen planus", 
            "mouth cancer", 
            "tongue cancer", 
            "syphilis", 
            "hiv/aids"
        ], 
        "url": "http://www.mayoclinic.org/symptoms/white-tongue/basics/definition/sym-20050676"
    }, 
    "yellow tongue": {
        "causes": [
            "black hairy tongue", 
            "geographic tongue", 
            "jaundice"
        ], 
        "url": "http://www.mayoclinic.org/symptoms/yellow-tongue/basics/definition/sym-20050595"
    }
}