var stars = [
  '[[;yellow;black]                                                                                                    ]',
  '[[;yellow;black]                                                                                                    ]',
  '[[;yellow;black]                           ..                                                                       ]',
  '[[;yellow;black]                                                             *                                      ]',
  '[[;yellow;black]                                                                                                    ]',
  '[[;yellow;black]                                                                                                    ]',
  '[[;yellow;black]                                                    .                                               ]',
  '[[;yellow;black]                                 ..                                                                 ]',
  '[[;yellow;black]                                                                       .                            ]',
  '[[;yellow;black]                                                                       .                            ]',
  '[[;yellow;black]                                                                                                    ]',
  '[[;yellow;black]                                                                                                    ]',
  '[[;yellow;black]              .                                                                              ..     ]',
  '[[;yellow;black]                                               .                                                    ]',
  '[[;yellow;black]                                                                   *                                ]',
  '[[;yellow;black]                                                                                   .                ]',
  '[[;yellow;black]                                                                                                    ]',
  '[[;yellow;black]                                         .                                                          ]',
  '[[;yellow;black]                    *                                                                               ]',
  '[[;yellow;black]                                                                                                    ]',
  '[[;yellow;black]                                                                                                    ]',
  '[[;yellow;black]                                                                                                    ]',
  '[[;yellow;black]                              .                                ..                                   ]',
  '[[;yellow;black]                                                                                                    ]',
  '[[;yellow;black]                                                                                                    ]',
  '[[;yellow;black]            .                                                                     .                 ]',
  '[[;yellow;black]                                                                                                    ]',
  '[[;yellow;black]                                                                                                    ]',
  '[[;yellow;black]                                          ..                                                        ]',
  '[[;yellow;black]                                                                                                    ]',
  '[[;yellow;black]                                                            ..                                      ]',
  '[[;yellow;black]                                                                                                    ]',
  '[[;yellow;black]           *                                                                                        ]',
  '[[;yellow;black]                                                                                                    ]',
  '[[;yellow;black]                                                                                                    ]',
  '[[;yellow;black]                                                                             ..                     ]',
  '[[;yellow;black]                                                                                                    ]'
];